### ISSUE TITLE
Tracking and creating a baseline for memory usage

### ISSUE THREAD

**Issue by twitu** [nautechsystems/nautilus_trader#1099]
New features and enhancements might cause memory leaks (like before! 😨) or increase memory usage significantly. To catch leaks and optimize usage, we first need to measure and establish a baseline. It'll help to measure memory for independent components as well full tests. Currently I can identify persistence layer and full back test as two candidates.

Previously [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) was very helpful in identifying memory usage before and after certain sections of code. So we can go with this.

**Comment by nilesh05apr** [comment]
@twitu can i work on this task please?

**Comment by twitu** [comment]
You're welcome to @nilesh05apr . If you're new here (hi 👋), you'll want to follow these steps to setup - https://github.com/nautechsystems/nautilus_trader#from-source.

In this repo, we mainly want to measure peak memory usage and memory leaks. [tracemalloc](https://docs.python.org/3/library/tracemalloc.html) is a good bet. Happy to hear your suggestions.

We want to establish baselines for full tests and persistence module for now. For full test you can consider instrumenting any of the files in `examples/backtest`. The idea is to check memory snapshot before and after the backtest and has been run and torn down.

Persistence is the module that loads data from disk. We've recently ported and want to do the same for it. You can take a look at file `test_persistence_module.py` and `test_perf_catalog.py` the tests using `PythonCatalog` as reference for how it's used.

Let me know if you have any questions 😄

**Comment by nilesh05apr** [comment]
Thanks @twitu for the guide, I will set up the project and will start my research.

**Comment by twitu** [comment]
@nilesh05apr any progress? Anything you're stuck on?

**Comment by nilesh05apr** [comment]
Hey @twitu I am looking for some alternate way to install on windows. I am getting some unknown errors while installing poetry.

**Comment by cjdsellers** [comment]
> Hey @twitu I am looking for some alternate way to install on windows. I am getting some unknown errors while installing poetry.

Hi @nilesh05apr 

Whats the error output?

**Comment by nilesh05apr** [comment]
hey @twitu do you know how to fix this?

=====================================================================
Nautilus Builder
=====================================================================
System: Windows AMD64
Traceback (most recent call last):
  File "D:\CodeBase\Projects\nautilus_trader\build.py", line 324, in <module>
    print(f"Clang:  {_get_clang_version()}")
  File "D:\CodeBase\Projects\nautilus_trader\build.py", line 235, in _get_clang_version
    result = subprocess.run(
  File "C:\Users\nilesh\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\nilesh\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\nilesh\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

Command ['C:\\Users\\nilesh\\AppData\\Local\\Temp\\tmpeodggb8_\\.venv\\Scripts\\python.exe', 'D:\\CodeBase\\Projects\\nautilus_trader\\build.py'] errored 
with the following return code 1

**Comment by cjdsellers** [comment]
Hey @nilesh05apr 

Looks like you don't have the clang compiler installed (required for the build).

**Comment by twitu** [comment]
@nilesh05apr are you facing any other issues with the installation?

**Comment by nilesh05apr** [comment]
no, but I am not able to resolve the previous error, i updated my visual studio and compilers.

**Comment by twitu** [comment]
The previous error indicated that `clang` was missing. Have you installed clang? If you open powershell and type `clang++ --version` it should report a version.

clang can be installed using visual studio. Perhaps check out this [SO answer](https://stackoverflow.com/a/63916235), it has the steps.

**Comment by nilesh05apr** [comment]
ohh Got it, there is some problem with installation in the clang, I will have to reinstall/modify the previous settings of visual studio.

**Comment by cjdsellers** [comment]
Given the progress of the Rust port and absence of any specific reports on leaks - closing this for now as efforts may be better spent elsewhere.

Anyone feel free to pick this up or provide any feedback though!
