### ISSUE TITLE
write_parquet() fails to write futures instrument data for some markets.

### ISSUE THREAD

**Issue by rterbush** [nautechsystems/nautilus_trader#1101]
# Bug Report

### Expected Behavior
Attempting to generate a Nautilus data library on ~20 or so futures markets. 

### Actual Behavior
I'm finding that in attempting to write the instrument data to parquet files, it fails for some instruments and not others.

### Steps to Reproduce the Problem

I'm using the following bit of code to write the instrument data:

```py
def process_dates(dirlist: list):
    cdates = {}
    for dir in dirlist:
        print(f"Processing dates for {dir.name} contracts...")
        for item in dir.iterdir():
            if item.is_file():
                symbol = item.name.split('.')[0]

                with lzma.open(item, "rt") as f:
                    lines = sum(bl.count('\n') for bl in blocks(f)) # type: ignore

                colnames = ['date','time','o','h','l','c','v']
                df = pd.read_csv(item, skiprows=(lines - 12),
                                 index_col=[0], parse_dates=[['date','time']], names=colnames, # type: ignore
                                 header=None, float_precision='round_trip', compression='infer')
                df = df.tz_localize(pytz.timezone('UTC'))
                expiry_date = df.last_valid_index() - (int(cm[symbol[:-3]]['info']['rollrule'][1:3]) * US_BUSINESS_DAY) # type: ignore
                ts_event = int(expiry_date.timestamp() * 1000)
                cdates.update({f"{symbol}": {'expiry_date': f"{expiry_date.strftime('%Y-%m-%d')}", 'ts_event': ts_event}})

    return cdates


def create_instruments(catalog: ParquetDataCatalog, datedict: dict):
    contracts = sorted(datedict.keys(), key=lambda x: (datedict[x]['expiry_date']))
    instruments = []
    for contract in contracts:
        instrument_dict = {}
        instrument_dict = cm[contract[:-3]]
        instrument_dict['id'] = f"{contract}.{cm[contract[:-3]]['venue']}"
        instrument_dict['native_symbol'] = contract
        instrument_dict['expiry_date'] = datedict[contract]['expiry_date']
        instrument_dict['ts_event'] = datedict[contract]['ts_event']
        instrument_dict['ts_init'] = datedict[contract]['ts_event']
        instruments.append(FuturesContract.from_dict(instrument_dict))

    write_objects(catalog=catalog, chunk=instruments)
```

The payload being written from the `instruments` list for a market that works looks like this:
```
[FuturesContract(id=YMZ09.CBOT, native_symbol=YMZ09, asset_class=INDEX, asset_type=FUTURE, quote_currency=USD, is_inverse=False, price_precision=0, price_increment=1, size_precision=0, size_increment=1, multiplier=5, lot_size=1, margin_init=0, margin_maint=0, maker_fee=0, taker_fee=0, info={}),
 FuturesContract(id=YMH10.CBOT, native_symbol=YMH10, asset_class=INDEX, asset_type=FUTURE, quote_currency=USD, is_inverse=False, price_precision=0, price_increment=1, size_precision=0, size_increment=1, multiplier=5, lot_size=1, margin_init=0, margin_maint=0, maker_fee=0, taker_fee=0, info={}),
```

The payload being written for a market that fails looks like this:
```
[FuturesContract(id=HGU09.COMEX, native_symbol=HGU09, asset_class=METAL, asset_type=FUTURE, quote_currency=USD, is_inverse=False, price_precision=4, price_increment=0.0005, size_precision=0, size_increment=1, multiplier=25000, lot_size=1, margin_init=0, margin_maint=0, maker_fee=0, taker_fee=0, info={}),
 FuturesContract(id=HGV09.COMEX, native_symbol=HGV09, asset_class=METAL, asset_type=FUTURE, quote_currency=USD, is_inverse=False, price_precision=4, price_increment=0.0005, size_precision=0, size_increment=1, multiplier=25000, lot_size=1, margin_init=0, margin_maint=0, maker_fee=0, taker_fee=0, info={}),
```

Backtrace for the error is:
```
Traceback (most recent call last):
  File "/Users/randy/Develop/_Personal/systemdev_base/scripts/parse_data_to_catalog.py", line 197, in <module>
    create_instruments(catalog, contract_dates)
  File "/Users/randy/Develop/_Personal/systemdev_base/scripts/parse_data_to_catalog.py", line 95, in create_instruments
    write_objects(catalog=catalog, chunk=instruments)
  File "/Users/randy/Develop/_Personal/nautilus_trader/nautilus_trader/persistence/external/core.py", line 391, in write_objects
    write_tables(catalog=catalog, tables=tables, **kwargs)
  File "/Users/randy/Develop/_Personal/nautilus_trader/nautilus_trader/persistence/external/core.py", line 256, in write_tables
    write_parquet(
  File "/Users/randy/Develop/_Personal/nautilus_trader/nautilus_trader/persistence/external/core.py", line 322, in write_parquet
    table = pa.Table.from_pandas(df, schema=schema)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/table.pxi", line 3490, in pyarrow.lib.Table.from_pandas
  File "pyarrow/table.pxi", line 3575, in pyarrow.lib.Table.from_arrays
  File "pyarrow/table.pxi", line 1398, in pyarrow.lib._sanitize_arrays
  File "pyarrow/array.pxi", line 347, in pyarrow.lib.asarray
  File "pyarrow/array.pxi", line 926, in pyarrow.lib.Array.cast
                df = pd.read_csv(item, skiprows=(lines - 12),
  File "/users/randy/bin/miniconda3/envs/nautilus/lib/python3.11/site-packages/pyarrow/compute.py", line 389, in cast
    return call_function("cast", [arr], options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pyarrow/_compute.pyx", line 560, in pyarrow._compute.call_function
  File "pyarrow/_compute.pyx", line 355, in pyarrow._compute.Function.call
  File "pyarrow/error.pxi", line 144, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Integer value 128 not in range: -128 to 127
```

The relevant line of code is here: https://github.com/nautechsystems/nautilus_trader/blob/e13b080469157a5efe23e09fba1f3a070fe166cf/nautilus_trader/persistence/external/core.py#L319

I've found that if you remove the schema from the parameters for the pyarrow.Table.from_pandas() call, it works on all market instruments. But fails for some markets, consistently, with schema.

Perhaps related is that I find that it is writing duplicate data to the parquet file. Not sure if that is expected, but certainly not desired. For example, if I run this process on ES data twice, I will have duplicate entries for all contracts even with identical ts_event timestamps.

### Specifications

- OS platform: tested on both Apple arm64 and Linux x86
- Python version: 3.11.3
- `nautilus_trader` version: 1.174.0 develop branch

**Comment by rterbush** [comment]
A few things I tried:

1. Upgraded pyarrow to 12.0.0
2. Upgraded pandas to 2.0.1
3. Reduced size of contract list of a failing market to equal number of ES market contracts.
4. Explicitly cast pandas columns to uint8 and uint64 to match the schema being used. (these are coming into the dataframe as unmatched data types)

**Comment by cjdsellers** [comment]
Hi @rterbush 

I would say this error is likely occurring because of one of the fields in the `FuturesContract` schema using `pa.int8()` keys, and the data being converted into an arrow table index contains a key value which goes out of range.

```
    FuturesContract: pa.schema(
        {
            "id": pa.dictionary(pa.int64(), pa.string()),
            "native_symbol": pa.string(),
            "underlying": pa.dictionary(pa.int16(), pa.string()),
            "asset_class": pa.dictionary(pa.int8(), pa.string()),
            "currency": pa.dictionary(pa.int16(), pa.string()),
            "price_precision": pa.uint8(),
            "size_precision": pa.uint8(),
            "price_increment": pa.dictionary(pa.int8(), pa.string()),
            "size_increment": pa.dictionary(pa.int8(), pa.string()),
            "multiplier": pa.dictionary(pa.int8(), pa.string()),
            "lot_size": pa.dictionary(pa.int8(), pa.string()),
            "expiry_date": pa.dictionary(pa.int8(), pa.string()),
            "ts_event": pa.uint64(),
            "ts_init": pa.uint64(),
        },
    ),
```

We did a pass a while ago extended many of the key widths, but not all. I'll do another pass later today which should unblock you here, but it will be another breaking change to the schemas - which is breaking again when we go all Rust. So a lot of movement here right now.

**Comment by cjdsellers** [comment]
I've pushed a potential fix up to `develop` which also includes an upgrade to `pyarrow` 12.0.0.

Please let me know how that goes for you :pray:

**Comment by cjdsellers** [comment]
We're also looking at redoing the writer, so avoiding duplicating into the dataset is something we'll ensure for v2.

**Comment by rterbush** [comment]
This has fixed the problem @cjdsellers 
Thanks for everyone's work here.

**Comment by cjdsellers** [comment]
Great to hear! closing this for now then.
