### ISSUE TITLE
install error ,ubuntu python3.10

### ISSUE THREAD

**Issue by xingtaonew** [nautechsystems/nautilus_trader#1113]
Building wheels for collected packages: nautilus_trader
  Building wheel for nautilus_trader (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for nautilus_trader (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      
      =====================================================================
      Nautilus Builder
      =====================================================================
      System: Linux x86_64
      Traceback (most recent call last):
        File "/tmp/pip-install-fyv2he34/nautilus-trader_2d9ad2c14f2b4552b134ad857a86cb63/build.py", line 324, in <module>
          print(f"Clang:  {_get_clang_version()}")
        File "/tmp/pip-install-fyv2he34/nautilus-trader_2d9ad2c14f2b4552b134ad857a86cb63/build.py", line 235, in _get_clang_version
          result = subprocess.run(
        File "/usr/lib/python3.10/subprocess.py", line 503, in run
          with Popen(*popenargs, **kwargs) as process:
        File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'clang'
      Traceback (most recent call last):
        File "/root/env3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/root/env3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/root/env3.10/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-p6o_1zia/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 57, in build_wheel
          return WheelBuilder.make_in(
        File "/tmp/pip-build-env-p6o_1zia/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 86, in make_in
          wb.build(target_dir=directory)
        File "/tmp/pip-build-env-p6o_1zia/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 121, in build
          self._build(zip_file)
        File "/tmp/pip-build-env-p6o_1zia/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 170, in _build
          self._run_build_script(self._package.build_script)
        File "/tmp/pip-build-env-p6o_1zia/overlay/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 230, in _run_build_script
          subprocess.check_call([self.executable.as_posix(), build_script])
        File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/root/env3.10/bin/python3.10', 'build.py']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for nautilus_trader
Failed to build nautilus_trader
ERROR: Could not build wheels for nautilus_trader, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip

**Comment by cjdsellers** [comment]
Hi @xingtaonew 

Thanks for your interest in Nautilus,

Looks like there isn't an available pre-compiled wheel available for your operating system on PyPI. This is why the package is attempting to install from source, are you on Ubuntu version 16 or earlier by any chance?

Then during the build, there is an error because the `clang` compiler is not installed on your machine (a required dependency). You could rectify this by running the following, then attempt to install again:
```
sudo apt-get install clang
```

As a heads up you'll also need Rust installed.

I'll also improve the error handling here because this block is meant to be called in this case:
```
        raise RuntimeError(
            "You are installing from source which requires the Clang compiler to be installed.\n"
            f"Error running clang: {e.stderr.decode()}",
        ) from e
```

I hope the above helps rectify the issue!
