### ISSUE TITLE
cannot compile `nautilus-pyo3` (lib)

### ISSUE THREAD

**Issue by graceyangfan** [nautechsystems/nautilus_trader#1149]
# Bug Report
cannot compile `nautilus-pyo3` (lib)
### Actual Behavior
```
Caused by:
  process didn't exit successfully: `rustc --crate-name nautilus_pyo3 --edition=2021 pyo3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C codegen-units=1 --cfg 'feature="default"' --cfg 'feature="extension-module"' -C metadata=1c22c62e367f1d45 --out-dir /home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/deps -C strip=symbols -L dependency=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/deps --extern nautilus_indicators=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/deps/libnautilus_indicators.rlib --extern nautilus_model=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/deps/libnautilus_model-87e05285b2bb6e78.rlib --extern nautilus_network=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/deps/libnautilus_network.rlib --extern nautilus_persistence=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/deps/libnautilus_persistence.rlib --extern pyo3=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/deps/libpyo3-9bf49cde7000b744.rlib '-Aclippy::drop_non_drop' -L native=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/build/openssl-sys-82f1d8ea6aec8c42/out/openssl-build/install/lib -L native=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/build/ring-95baaed4d2615021/out -L native=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/build/bzip2-sys-6df41f44c7d5bf19/out/lib -L native=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/build/lzma-sys-cd02add58bb235f5/out -L native=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/build/zstd-sys-08e6086871c826c3/out -L native=/home/ubuntu/nautilus_trader-develop/nautilus_core/target/release/build/lz4-sys-0eec72c753de5f3a/out` (signal: 9, SIGKILL: kill)
Traceback (most recent call last):
  File "/home/ubuntu/nautilus_trader-develop/build.py", line 95, in _build_rust_libs
    subprocess.run(
  File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cargo', 'build', '--release', '--all-features']' returned non-zero exit status 101.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/nautilus_trader-develop/build.py", line 345, in <module>
    build()
  File "/home/ubuntu/nautilus_trader-develop/build.py", line 299, in build
    _build_rust_libs()
  File "/home/ubuntu/nautilus_trader-develop/build.py", line 102, in _build_rust_libs
    f"Error running cargo: {e.stderr.decode()}",
AttributeError: 'NoneType' object has no attribute 'decode'
```

### Steps to Reproduce the Problem

1.BUILD_MODE=release poetry run python build.py

### Specifications

- OS platform:Ubuntun20.04
- Python version:python 3.10.8
- `nautilus_trader` version:v1.175.0

**Comment by graceyangfan** [comment]
close This,I have try to reinstall the system to clean the older-version nautilus_trader building file,This building error may caused by the oder-version building files
