### ISSUE TITLE
kw_only=True required on SandboxExecutionClientConfig

### ISSUE THREAD

**Issue by pontus-lund** [nautechsystems/nautilus_trader#1227]
# Bug Report

### Expected Behavior
```
from nautilus_trader.adapters.sandbox.config import SandboxExecutionClientConfig
from nautilus_trader.adapters.sandbox.execution import SandboxExecutionClient
from nautilus_trader.adapters.sandbox.factory import SandboxLiveExecClientFactory

if __name__ == '__main__':
    print("wouldn't it be nice?")
```
prints "wouldn't it be nice?"

### Actual Behavior
```
(.venv) pontus@rocinante:~/code/ts/test_import$ python main.py
Traceback (most recent call last):
  File "/home/pontus/code/ts/test_import/main.py", line 1, in <module>
    from nautilus_trader.adapters.sandbox.config import SandboxExecutionClientConfig
  File "/home/pontus/code/ts/test_import/.venv/lib/python3.10/site-packages/nautilus_trader/adapters/sandbox/config.py", line 19, in <module>
    class SandboxExecutionClientConfig(LiveExecClientConfig, frozen=True):
TypeError: Required field 'venue' cannot follow optional fields. Either reorder the struct fields, or set `kw_only=True` in the struct definition.
(.venv) pontus@rocinante:~/code/ts/test_import$ 
```

### Steps to Reproduce the Problem

Run this code:
```
from nautilus_trader.adapters.sandbox.config import SandboxExecutionClientConfig
from nautilus_trader.adapters.sandbox.execution import SandboxExecutionClient
from nautilus_trader.adapters.sandbox.factory import SandboxLiveExecClientFactory

if __name__ == '__main__':
    print("wouldn't it be nice?")
```

### Specifications

- OS platform: Linux
- Python version: 3.10
- `nautilus_trader` version: 1.178

**Comment by cjdsellers** [comment]
Now fixed from 63aca32886a33469e3ceb5ed8cb68ffd95f063cd.
