### ISSUE TITLE
backtest: using multiple BacktestDataConfig with start and end date set does not run

### ISSUE THREAD

**Issue by davidsblom** [nautechsystems/nautilus_trader#1304]
# Bug Report

When the start and end date are set with 2 data sources, the backtest doesn't run. I'm using this configuration:

```python
data = [
        BacktestDataConfig(
            catalog_path=str(catalog.path),
            data_cls=QuoteTick,
            instrument_id=instrument.id.value,
            batch_size=50000,
            start_time=start_time,
            end_time=end_time,
        ),
        BacktestDataConfig(
            catalog_path=str(catalog.path),
            data_cls=TradeTick,
            instrument_id=instrument.id.value,
            start_time=start_time,
            end_time=end_time,
        ),
    ]
```

When the start time and end time are not specified, the backtest runs as expected.

``` python
data = [
        BacktestDataConfig(
            catalog_path=str(catalog.path),
            data_cls=QuoteTick,
            instrument_id=instrument.id.value,
            batch_size=50000,
            # start_time=start_time,
            # end_time=end_time,
        ),
        BacktestDataConfig(
            catalog_path=str(catalog.path),
            data_cls=TradeTick,
            instrument_id=instrument.id.value,
            # start_time=start_time,
            # end_time=end_time,
        ),
    ]
```

### Expected Behavior
The backtest runs without any isues.

### Actual Behavior
The backtest is not started, but ends directly. An exception is thrown when `engine.end()` is called.

```
2023-10-24T10:47:45.485717000Z [INF] BACKTESTER-001.BacktestEngine: Initialized in 1619ms.
2023-10-24T10:47:45.486800000Z [INF] BACKTESTER-001.SimulatedExchange(BINANCE): OmsType=NETTING
2023-10-24T10:47:45.486976000Z [INF] BACKTESTER-001.ExecClient-BINANCE: READY.
2023-10-24T10:47:45.487176000Z [INF] BACKTESTER-001.SimulatedExchange(BINANCE): Registered ExecutionClient-BINANCE.
2023-10-24T10:47:45.487181000Z [INF] BACKTESTER-001.ExecEngine: Registered ExecutionClient-BINANCE.
2023-10-24T10:47:45.487185000Z [INF] BACKTESTER-001.BacktestEngine: Added SimulatedExchange(id=BINANCE, oms_type=NETTING, account_type=CASH).
2023-10-24T10:47:45.512945000Z [INF] BACKTESTER-001.DataClient-BINANCE: READY.
2023-10-24T10:47:45.513139000Z [INF] BACKTESTER-001.DataEngine: Registered BINANCE.
2023-10-24T10:47:45.513752000Z [DBG] BACKTESTER-001.Cache: Added instrument ETHUSDT.BINANCE.
2023-10-24T10:47:45.514012000Z [INF] BACKTESTER-001.SimulatedExchange(BINANCE): Added instrument ETHUSDT.BINANCE and created matching engine.
2023-10-24T10:47:45.514017000Z [INF] BACKTESTER-001.BacktestEngine: Added ETHUSDT.BINANCE Instrument.
2023-10-24T10:47:46.996107000Z [INF] BACKTESTER-001.BacktestEngine: =================================================================
2023-10-24T10:47:46.996129000Z [INF] BACKTESTER-001.BacktestEngine:  BACKTEST POST-RUN
2023-10-24T10:47:46.996130000Z [INF] BACKTESTER-001.BacktestEngine: =================================================================
2023-10-24T10:47:46.996143000Z [INF] BACKTESTER-001.BacktestEngine: Run config ID:  None
2023-10-24T10:47:46.996146000Z [INF] BACKTESTER-001.BacktestEngine: Run ID:         None
2023-10-24T10:47:46.996146001Z [INF] BACKTESTER-001.BacktestEngine: Run started:    None
2023-10-24T10:47:46.996338000Z [INF] BACKTESTER-001.BacktestEngine: Run finished:   2023-10-24 10:47:46.995752+00:00
Traceback (most recent call last):
  File "/Users/davidblom/repositories/market-master/backtest/rl_app.py", line 104, in <module>
    main()
  File "/Users/davidblom/repositories/market-master/backtest/rl_app.py", line 98, in main
    node.run()
  File "/Users/davidblom/Library/Caches/pypoetry/virtualenvs/market-master-pSszKNue-py3.11/lib/python3.11/site-packages/nautilus_trader/backtest/node.py", line 127, in run
    result = self._run(
             ^^^^^^^^^^
  File "/Users/davidblom/Library/Caches/pypoetry/virtualenvs/market-master-pSszKNue-py3.11/lib/python3.11/site-packages/nautilus_trader/backtest/node.py", line 232, in _run
    self._run_streaming(
  File "/Users/davidblom/Library/Caches/pypoetry/virtualenvs/market-master-pSszKNue-py3.11/lib/python3.11/site-packages/nautilus_trader/backtest/node.py", line 293, in _run_streaming
    engine.end()
  File "nautilus_trader/backtest/engine.pyx", line 936, in nautilus_trader.backtest.engine.BacktestEngine.end
  File "nautilus_trader/backtest/engine.pyx", line 1241, in nautilus_trader.backtest.engine.BacktestEngine._log_post_run
TypeError: unsupported operand type(s) for -: 'Timestamp' and 'NoneType'
```

### Steps to Reproduce the Problem

1. Setup a streaming back test using Parquet datasets as input.
2. Include both QuoteTicks as well as TradeTicks 
3. Run the backtest

### Specifications

- OS platform: OS X
- Python version: 3.11
- `nautilus_trader` version: 1.179.0 release

**Comment by cjdsellers** [comment]
Hi @davidsblom 

I'm debugging this, what are the actual values you're using for `start_time` and `end_time` there?

**Comment by davidsblom** [comment]
hi @cjdsellers  many thanks that you are looking into this. here is the complete code snippet with the strategy info stripped.

```python
instrument = TestInstrumentProvider.ethusdt_binance()
catalog = ParquetDataCatalog(args.catalog_path)

start_time = dt_to_unix_nanos(pd.Timestamp("2022-07-01", tz="UTC"))
end_time = dt_to_unix_nanos(pd.Timestamp("2020-07-02", tz="UTC"))

data = [
  BacktestDataConfig(
      catalog_path=str(catalog.path),
      data_cls=QuoteTick,
      instrument_id=instrument.id.value,
      batch_size=5000,
      start_time=start_time,
      end_time=end_time,
  ),
  BacktestDataConfig(
      catalog_path=str(catalog.path),
      data_cls=TradeTick,
      instrument_id=instrument.id.value,
      batch_size=5000,
      start_time=start_time,
      end_time=end_time,
  ),
]

engine = BacktestEngineConfig(
  strategies=[
      ImportableStrategyConfig()
  ],
  logging=LoggingConfig(log_level="DEBUG"),  # Lower to `INFO` to see more logging about orders, events, etc.
)

# venue = Venue("BINANCE")
venue = BacktestVenueConfig(
  name="BINANCE",
  oms_type="NETTING",
  account_type="CASH",
  starting_balances=["1_000_000 USDT"],
)

config = BacktestRunConfig(
  engine=engine,
  venues=[venue],
  data=data,
  batch_size_bytes=5000 * 80,
)

node = BacktestNode(configs=[config])

node.run()

logging.info("Done")
```

**Comment by davidsblom** [comment]
hmm looking at my own code it seems that the end date is before the start date. let me test again.

**Comment by davidsblom** [comment]
yes it works :) apologies for the confusion. maybe we could add a validation that end_time >= start_time to find these mistakes quickly

**Comment by davidsblom** [comment]
Clsing since it is not a bug.

**Comment by davidsblom** [comment]
@cjdsellers  I've created a pull request to validate this. https://github.com/nautechsystems/nautilus_trader/pull/1311/files
