### ISSUE TITLE
Error if got external order on account

### ISSUE THREAD

**Issue by Tzumx** [nautechsystems/nautilus_trader#1365]
# Bug Report
Not sure if it's a bug, but report anyway.
Error is nautilus strategy when send order by external request

### Expected Behavior
Reconciling OrderStatusReport as it is for nautilus trades.

### Actual Behavior
```
2023-11-24T09:53:36.819440951Z [ERR] TRADER-001.ExecClient-BINANCE: Error on handling b'{"stream":"KagzbhvWO18Q86LU6GXkQjLko9f9o1n1nIMcOLL7T9YZhUiRgOX","data":{"e":"executionReport","E":1700819616686,"s":"MANAUSDT","c":"zYEykTgeC7DrJ6ynG","S":"SELL","o":"MARKET","f":"GTC","q":"206.00000000","p":"0.00000000","P":"0.00000000","F":"0.00000000","g":-1,"C":"","x":"NEW","X":"NEW","r":"NONE","i":2127790546,"l":"0.00000000","z":"0.00000000","L":"0.00000000","n":"0","N":null,"T":1700819616685,"t":-1,"I":4437986403,"w":true,"m":false,"M":false,"O":1700819616685,"Z":"0.00000000","Y":"0.00000000","Q":"0.00000000","W":1700819616685,"V":"EXPIRE_MAKER"}}'
ValueError(The 'value' string argument was invalid, was '')
Traceback (most recent call last):
  File "/home/user/envs/nautilus/lib/python3.10/site-packages/nautilus_trader/adapters/binance/spot/execution.py", line 216, in _handle_user_ws_message
    self._spot_user_ws_handlers[wrapper.data.e](raw)
  File "/home/user/envs/nautilus/lib/python3.10/site-packages/nautilus_trader/adapters/binance/spot/execution.py", line 226, in _handle_execution_report
    order_msg.data.handle_execution_report(self)
  File "/home/user/envs/nautilus/lib/python3.10/site-packages/nautilus_trader/adapters/binance/spot/schemas/user.py", line 221, in handle_execution_report
    client_order_id = ClientOrderId(client_order_id_str)
  File "nautilus_trader/model/identifiers.pyx", line 713, in nautilus_trader.model.identifiers.ClientOrderId.__init__
  File "nautilus_trader/core/correctness.pyx", line 795, in nautilus_trader.core.correctness.Condition.valid_string

2023-11-24T09:53:36.820459974Z [ERR] TRADER-001.ExecClient-BINANCE: Error on handling b'{"stream":"KagzbhvWO18Q86LU6GXkQjLko9f9o1n1nIMcOLL7T9YZhUiRgOX","data":{"e":"executionReport","E":1700819616686,"s":"MANAUSDT","c":"zYEykTgeC7DrJ6ynG","S":"SELL","o":"MARKET","f":"GTC","q":"206.00000000","p":"0.00000000","P":"0.00000000","F":"0.00000000","g":-1,"C":"","x":"TRADE","X":"FILLED","r":"NONE","i":2127790546,"l":"206.00000000","z":"206.00000000","L":"0.41330000","n":"0.00027091","N":"BNB","T":1700819616685,"t":195784884,"I":4437986404,"w":false,"m":false,"M":true,"O":1700819616685,"Z":"85.13980000","Y":"85.13980000","Q":"0.00000000","W":1700819616685,"V":"EXPIRE_MAKER"}}'
ValueError(The 'value' string argument was invalid, was '')
Traceback (most recent call last):
  File "/home/user/envs/nautilus/lib/python3.10/site-packages/nautilus_trader/adapters/binance/spot/execution.py", line 216, in _handle_user_ws_message
    self._spot_user_ws_handlers[wrapper.data.e](raw)
  File "/home/user/envs/nautilus/lib/python3.10/site-packages/nautilus_trader/adapters/binance/spot/execution.py", line 226, in _handle_execution_report
    order_msg.data.handle_execution_report(self)
  File "/home/user/envs/nautilus/lib/python3.10/site-packages/nautilus_trader/adapters/binance/spot/schemas/user.py", line 221, in handle_execution_report
    client_order_id = ClientOrderId(client_order_id_str)
  File "nautilus_trader/model/identifiers.pyx", line 713, in nautilus_trader.model.identifiers.ClientOrderId.__init__
  File "nautilus_trader/core/correctness.pyx", line 795, in nautilus_trader.core.correctness.Condition.valid_string
```

### Steps to Reproduce the Problem

1. Run any nautilus strategy.
2. Send order by core `python-binance` package (I sent market on spot market `binance_client.create_order()`)
3. Got error in nautilus

### Specifications

- OS platform: Ubuntu 22.04
- Python version: 3.10
- `nautilus_trader` version: 1.180

**Comment by cjdsellers** [comment]
Thanks for the report @Tzumx

I think Nautilus is correctly raising a `ValueError` here because there is no client order ID. I think if you submit an order via the web GUI there is some kind of client order ID, but if you manually submit and specifically omit a client order ID or pass the empty string, then it's considered invalid by the platform.

I don't think it would be a good idea to be lenient to this, and for example assign a `"NULL"` or `"None"` client order ID. Better that we fail fast like this, than allow invalid orders into the system I think?

Closing this for now, as the system isn't behaving out of spec.
