### ISSUE TITLE
Format error outputs for BacktestNode exceptions

### ISSUE THREAD

**Issue by kbs-code** [nautechsystems/nautilus_trader#1388]
# Feature Request
Code reference: https://github.com/nautechsystems/nautilus_trader/blob/master/nautilus_trader/backtest/node.py

I was trying to run a high-level backtest and saw some output in the terminal.  Most of it was formatted fine except for one block of text.  Node.py is printing my configs unformatted when I misconfigured something in my backtest.  This makes it harder to read error output and debug my backtests.  This seems to be coming from lines 129-142 of Node.py:
```
         for config in self._configs:
            try:
                result = self._run(
                    run_config_id=config.id,
                    engine_config=config.engine,
                    venue_configs=config.venues,
                    data_configs=config.data,
                    batch_size_bytes=config.batch_size_bytes,
                )
                results.append(result)
            except Exception as e:
                # Broad catch all prevents a single backtest run from halting
                # the execution of the other backtests (such as a zero balance exception).
                print(f"Error running {config}: {e}")
```

I tried formatting the output on my end using various try/except statements, but none improved it.    
![backtest_error_output](https://github.com/nautechsystems/nautilus_trader/assets/42240122/51d28a5e-2097-49b3-bc8d-2f3fa60a86fe)

**Comment by cjdsellers** [comment]
[Now implemented](ffc1bf64bccc9ad030c286f1da83b0918439cc87) a full stack trace on backtest node errors, as well as formatted logs of the configuration:

```
2020-03-25T10:45:00.000000000Z [ERROR] EXAMPLE-PORTFOLIO.BacktestNode: Error running backtest
AssertionError()
Traceback (most recent call last):
  File "/nautilus_trader/nautilus_trader/backtest/node.py", line 214, in run
    result = self._run(
        run_config_id=config.id,
    ...<6 lines>...
        end=config.end,
    )
  File "/nautilus_trader/nautilus_trader/backtest/node.py", line 277, in _run
    self._run_oneshot(
    ~~~~~~~~~~~~~~~~~^
        run_config_id=run_config_id,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        end=end,
        ^^^^^^^^
    )
    ^
  File "/nautilus_trader/nautilus_trader/backtest/node.py", line 460, in _run_oneshot
    engine.run(start=start, end=end, run_config_id=run_config_id)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "nautilus_trader/backtest/engine.pyx", line 983, in nautilus_trader.backtest.engine.BacktestEngine.run
  File "nautilus_trader/backtest/engine.pyx", line 1220, in nautilus_trader.backtest.engine.BacktestEngine._run
  File "nautilus_trader/backtest/exchange.pyx", line 903, in nautilus_trader.backtest.exchange.SimulatedExchange.process
  File "nautilus_trader/backtest/exchange.pyx", line 941, in nautilus_trader.backtest.exchange.SimulatedExchange._process_trading_command
  File "nautilus_trader/backtest/matching_engine.pyx", line 927, in nautilus_trader.backtest.matching_engine.OrderMatchingEngine.process_order
  File "nautilus_trader/backtest/matching_engine.pyx", line 1019, in nautilus_trader.backtest.matching_engine.OrderMatchingEngine._process_market_order
  File "nautilus_trader/backtest/matching_engine.pyx", line 1685, in nautilus_trader.backtest.matching_engine.OrderMatchingEngine.fill_market_order
  File "nautilus_trader/backtest/matching_engine.pyx", line 1599, in nautilus_trader.backtest.matching_engine.OrderMatchingEngine.determine_market_price_and_volume
  File "nautilus_trader/model/book.pyx", line 663, in nautilus_trader.model.book.OrderBook.simulate_fills

2020-03-25T10:45:00.000000000Z [INFO] EXAMPLE-PORTFOLIO.BacktestNode: Engine config:
2020-03-25T10:45:00.000000000Z [INFO] EXAMPLE-PORTFOLIO.BacktestNode: {
  "environment": "backtest",
  "trader_id": "EXAMPLE-PORTFOLIO",
  "instance_id": null,
  "cache": null,
  "message_bus": null,
  "data_engine": {
    "time_bars_interval_type": "left-open",
    "time_bars_timestamp_on_close": true,
    "time_bars_skip_first_non_full_bar": false,
    "time_bars_build_with_no_updates": true,
    "time_bars_origins": null,
    "validate_data_sequence": false,
    "buffer_deltas": false,
    "external_clients": null,
    "debug": false
  },
  "risk_engine": {
    "bypass": true,
    "max_order_submit_rate": "100/00:00:01",
    "max_order_modify_rate": "100/00:00:01",
    "max_notional_per_order": {},
    "debug": false
  },
  "exec_engine": {
    "load_cache": true,
    "manage_own_order_books": false,
    "snapshot_orders": false,
    "snapshot_positions": false,
    "snapshot_positions_interval_secs": null,
    "debug": false
  },
  "portfolio": null,
  "emulator": null,
  "streaming": null,
  "catalogs": [],
  "actors": [],
  "strategies": [],
  "exec_algorithms": [],
  "controller": {
    "controller_path": "example_controller:ExamplePortfolioController",
    "config_path": "example_controller:ExamplePortfolioControllerConfig",
    "config": {
      "venue": "BYBIT",
      "instruments": [
        "BTCUSDT-LINEAR"
      ],
      "traded_instruments": 1
    }
  },
  "load_state": false,
  "save_state": false,
  "loop_debug": false,
  "logging": {
    "log_level": "DEBUG",
    "log_level_file": "DEBUG",
    "log_directory": null,
    "log_file_name": null,
    "log_file_format": null,
    "log_colors": true,
    "log_component_levels": {
      "BacktestEngine": "DEBUG"
    },
    "bypass_logging": false,
    "print_config": false,
    "use_pyo3": false,
    "clear_log_file": false
  },
  "timeout_connection": 60.0,
  "timeout_reconciliation": 30.0,
  "timeout_portfolio": 10.0,
  "timeout_disconnection": 10.0,
  "timeout_post_stop": 10.0,
  "timeout_shutdown": 5.0,
  "run_analysis": true
}
2020-03-25T10:45:00.000000000Z [INFO] EXAMPLE-PORTFOLIO.BacktestNode: Venue configs:
2020-03-25T10:45:00.000000000Z [INFO] EXAMPLE-PORTFOLIO.BacktestNode: {
  "name": "BYBIT",
  "oms_type": "NETTING",
  "account_type": "MARGIN",
  "starting_balances": [
    "10_000 USDT"
  ],
  "base_currency": "USDT",
  "default_leverage": 1.0,
  "leverages": null,
  "book_type": "L1_MBP",
  "routing": false,
  "frozen_account": false,
  "reject_stop_orders": true,
  "support_gtd_orders": true,
  "support_contingent_orders": true,
  "use_position_ids": true,
  "use_random_ids": false,
  "use_reduce_only": true,
  "bar_execution": true,
  "bar_adaptive_high_low_ordering": false,
  "trade_execution": false,
  "modules": null
}
2020-03-25T10:45:00.000000000Z [INFO] EXAMPLE-PORTFOLIO.BacktestNode: Data configs:
2020-03-25T10:45:00.000000000Z [INFO] EXAMPLE-PORTFOLIO.BacktestNode: {
  "catalog_path": "/nautilus_trader/temp/example/catalog",
  "data_cls": "nautilus_trader.model.data:Bar",
  "catalog_fs_protocol": null,
  "catalog_fs_storage_options": null,
  "instrument_id": "BTCUSDT-LINEAR.BYBIT",
  "start_time": 1577836800000000000,
  "end_time": 1741305600000000000,
  "filter_expr": null,
  "client_id": "BYBIT",
  "metadata": null,
  "bar_spec": null,
  "instrument_ids": null,
  "bar_types": [
    "BTCUSDT-LINEAR.BYBIT-15-MINUTE-LAST-EXTERNAL"
  ]
}
[2025-04-07 11:42:49.028030] finshed.
Total duration = [0:00:00.650850].

```
