### ISSUE TITLE
Binance Order Status EXPIRED_IN_MATCH

### ISSUE THREAD

**Issue by doublier1** [nautechsystems/nautilus_trader#1437]
# Bug Report

Another Enum mismatch for Binance:

```
2024-01-05T16:47:41.907499001Z [ERR] A23R-spot-001.ExecClient-BINANCE: Cannot reconcile execution state
ValidationError(Invalid enum value 'EXPIRED_IN_MATCH' - at `$[979].status`)
Traceback (most recent call last):
  File "/Users/lawrence/Library/Caches/pypoetry/virtualenvs/alpha23-nautilus-hCXNsH36-py3.11/lib/python3.11/site-packages/nautilus_trader/live/execution_client.py", line 447, in generate_mass_status
    reports = await asyncio.gather(
              ^^^^^^^^^^^^^^^^^^^^^
```

See here:  https://binance-docs.github.io/apidocs/spot/en/#public-api-definitions

Added in January 2023, but I guess rarely seen.

### Expected Behavior

Should handle enum EXPIRED_IN_MATCH for OrderStatus

### Actual Behavior

Throws Exception:
```
2024-01-05T16:47:41.907499001Z [ERR] A23R-spot-001.ExecClient-BINANCE: Cannot reconcile execution state
ValidationError(Invalid enum value 'EXPIRED_IN_MATCH' - at `$[979].status`)
Traceback (most recent call last):
  File "/Users/lawrence/Library/Caches/pypoetry/virtualenvs/alpha23-nautilus-hCXNsH36-py3.11/lib/python3.11/site-packages/nautilus_trader/live/execution_client.py", line 447, in generate_mass_status
    reports = await asyncio.gather(
              ^^^^^^^^^^^^^^^^^^^^^
```

### Steps to Reproduce the Problem

Difficult to reproduce, but Binance docs say:

New order status: EXPIRED_IN_MATCH - This means that the order expired due to STP being triggered.

Where STP means (self trade protection), so I'm guessing this happens when you have multiple engines connecting to the same account.

### Specifications

- OS platform: MacOS X
- Python version: 3.11.4
- `nautilus_trader` version: 1.182.0

**Comment by cjdsellers** [comment]
Hi @doublier1 

Thanks again for the report. 

I've added this member to the enum, and for the translation went with a Nautilus `OrderStatus.CANCELED` as the order was canceled by the exchange, thoughts?

Closing this for now as fix has been pushed to `develop` branch.

**Comment by doublier1** [comment]
Confirmed it's working for me now
