### ISSUE TITLE
Circular import error

### ISSUE THREAD

**Issue by cuberone** [nautechsystems/nautilus_trader#1485]
# Bug Report

```
Traceback (most recent call last):
  File "/Users/ik/projects/nautilus_trader/examples/live/app.py", line 6, in <module>
    from nautilus_trader.examples.algorithms.twap_adoptive import (
  File "/Users/ik/projects/nautilus_trader/nautilus_trader/examples/algorithms/twap_adoptive.py", line 15, in <module>
    from nautilus_trader.execution.algorithm import ExecAlgorithm
  File "nautilus_trader/execution/algorithm.pyx", line 1, in init nautilus_trader.execution.algorithm
    # -------------------------------------------------------------------------------------------------
  File "nautilus_trader/common/actor.pyx", line 1, in init nautilus_trader.common.actor
    # -------------------------------------------------------------------------------------------------
  File "/Users/ik/projects/nautilus_trader/nautilus_trader/cache/__init__.py", line 23, in <module>
    from nautilus_trader.cache.cache import Cache
  File "nautilus_trader/cache/cache.pyx", line 1, in init nautilus_trader.cache.cache
    # -------------------------------------------------------------------------------------------------
  File "/Users/ik/projects/nautilus_trader/nautilus_trader/portfolio/__init__.py", line 20, in <module>
    from nautilus_trader.portfolio.portfolio import Portfolio
  File "nautilus_trader/portfolio/portfolio.pyx", line 1, in init nautilus_trader.portfolio.portfolio
    # -------------------------------------------------------------------------------------------------
  File "nautilus_trader/execution/manager.pyx", line 1, in init nautilus_trader.execution.manager
    # -------------------------------------------------------------------------------------------------
  File "/Users/ik/projects/nautilus_trader/nautilus_trader/trading/__init__.py", line 24, in <module>
    from nautilus_trader.trading.controller import Controller
  File "/Users/ik/projects/nautilus_trader/nautilus_trader/trading/controller.py", line 20, in <module>
    from nautilus_trader.trading.trader import Trader
  File "/Users/ik/projects/nautilus_trader/nautilus_trader/trading/trader.py", line 39, in <module>
    from nautilus_trader.execution.algorithm import ExecAlgorithm
ImportError: cannot import name 'ExecAlgorithm' from partially initialized module 'nautilus_trader.execution.algorithm' (most likely due to a circular import) (/Users/ik/projects/nautilus_trader/nautilus_trader/execution/algorithm.cpython-311-darwin.so)
```

### Steps to Reproduce the Problem

1. add any ExecAlgorithm to the application 
1.  make clean
2. poetry install --only main --all-extras
3. poetry run python -m examples.live.app

### Specifications

- OS platform:
- `nautilus_trader` version: today development branch

**Comment by cjdsellers** [comment]
Hi @cuberone

Thanks for the report on this.

With the way configuration was setup, there was a high risk of circular imports. 

Configuration has now been reorganized on latest `develop` so that each subpackage has its own `config` module (when required), with all configs remaining re-exported from `nautilus_trader.config` (so I don't expect the changes to break many imports in user code).

Closing this for now, but please let me know if this still hasn't fixed your issue.
