### ISSUE TITLE
Compliation failed at master branch

### ISSUE THREAD

**Issue by VeraLyu** [nautechsystems/nautilus_trader#1561]
# Bug Report
Compilation failed for nautilus-pyo3 for ubuntu 22.04.4

### Expected Behavior
Successful compilation for nautilus

### Actual Behavior
   Compiling nautilus-pyo3 v0.21.0 (/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/pyo3)
error: could not compile `nautilus-pyo3` (lib)

Caused by:
  process didn't exit successfully: `/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name nautilus_pyo3 --edition=2021 pyo3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=483 --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C codegen-units=1 --cfg 'feature="default"' --cfg 'feature="extension-module"' --cfg 'feature="ffi"' -C metadata=72cd39dd07d8eee4 --out-dir /home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps -C strip=symbols -L dependency=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps --extern nautilus_accounting=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps/libnautilus_accounting.rlib --extern nautilus_adapters=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps/libnautilus_adapters.rlib --extern nautilus_common=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps/libnautilus_common-4da3f982ac260780.rlib --extern nautilus_core=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps/libnautilus_core-95504a6c0d78ba69.rlib --extern nautilus_indicators=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps/libnautilus_indicators.rlib --extern nautilus_infrastructure=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps/libnautilus_infrastructure.rlib --extern nautilus_model=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps/libnautilus_model-c233644606a82176.rlib --extern nautilus_network=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps/libnautilus_network.rlib --extern nautilus_persistence=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps/libnautilus_persistence.rlib --extern pyo3=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/deps/libpyo3-e3383ff000a93381.rlib '-Aclippy::drop_non_drop' -L native=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/build/ring-bc232175097bcbeb/out -L native=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/build/bzip2-sys-a8739cc6e4bae5cd/out/lib -L native=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/build/lzma-sys-8ce34e72b1664844/out -L native=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/build/zstd-sys-30b77ed6b6bbfc1f/out -L native=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/build/openssl-sys-bd6469625ad1f35b/out/openssl-build/install/lib -L native=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/build/blake3-b7dc01a582b4f2de/out -L native=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/build/blake3-b7dc01a582b4f2de/out -L native=/home/ubuntu/crypto_level2/nautilus_trader/nautilus_core/target/release/build/libsqlite3-sys-4dd4e2abcdd72d05/out` (signal: 9, SIGKILL: kill)
Traceback (most recent call last):
  File "/home/ubuntu/crypto_level2/nautilus_trader/build.py", line 95, in _build_rust_libs
    subprocess.run(
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cargo', 'build', '--release', '--all-features']' returned non-zero exit status 101.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/crypto_level2/nautilus_trader/build.py", line 354, in <module>
    build()
  File "/home/ubuntu/crypto_level2/nautilus_trader/build.py", line 306, in build
    _build_rust_libs()
  File "/home/ubuntu/crypto_level2/nautilus_trader/build.py", line 101, in _build_rust_libs
    raise RuntimeError(
RuntimeError: Error running cargo: Command '['cargo', 'build', '--release', '--all-features']' returned non-zero exit status 101.

### Steps to Reproduce the Problem

1. follow the instruction on "Get started" page "Installation" - "From Source"

### Specifications

- OS platform: ubuntu 22.04.4
- Python version:python 3.10.12
- `nautilus_trader` version: community master

**Comment by VeraLyu** [comment]
got oom kill dmesg, so it is my machine memory limit. close bug
