### ISSUE TITLE
Error on backtest/data_producer.pyx:170L

### ISSUE THREAD

**Issue by ian-wazowski** [nautechsystems/nautilus_trader#174]
```
2021-01-10T19:53:31.983Z [INF] BacktestEngine: =================================================================
2021-01-10T19:53:31.983Z [INF] BacktestEngine:  NAUTILUS TRADER - Algorithmic Trading Platform
2021-01-10T19:53:31.983Z [INF] BacktestEngine:  by Nautech Systems Pty Ltd.
2021-01-10T19:53:31.983Z [INF] BacktestEngine:  Copyright (C) 2015-2020. All rights reserved.
2021-01-10T19:53:31.983Z [INF] BacktestEngine: =================================================================
2021-01-10T19:53:31.983Z [INF] BacktestEngine:
2021-01-10T19:53:31.983Z [INF] BacktestEngine:                             .......
2021-01-10T19:53:31.983Z [INF] BacktestEngine:                          .............
2021-01-10T19:53:31.983Z [INF] BacktestEngine:     .                  ......... .......
2021-01-10T19:53:31.984Z [INF] BacktestEngine:    .                  ......... .. .......
2021-01-10T19:53:31.984Z [INF] BacktestEngine:    .                 ......',,,,'..........
2021-01-10T19:53:31.984Z [INF] BacktestEngine:    ..               ......::,,''';,.........
2021-01-10T19:53:31.984Z [INF] BacktestEngine:    ..                ....'o:;oo;..:'..... ''
2021-01-10T19:53:31.984Z [INF] BacktestEngine:     ..               ......,;,,..,:'.........
2021-01-10T19:53:31.984Z [INF] BacktestEngine:     ..                .........';:'..... ...
2021-01-10T19:53:31.984Z [INF] BacktestEngine:      ..                 .......'..... .'. .'
2021-01-10T19:53:31.984Z [INF] BacktestEngine:       ..                   .....    .. .. ..
2021-01-10T19:53:31.984Z [INF] BacktestEngine:        ..                           .' ....
2021-01-10T19:53:31.984Z [INF] BacktestEngine:          ..                         .. .'.
2021-01-10T19:53:31.984Z [INF] BacktestEngine:           ....                     .....
2021-01-10T19:53:31.984Z [INF] BacktestEngine:              ....                ..'..
2021-01-10T19:53:31.984Z [INF] BacktestEngine:                  ..................
2021-01-10T19:53:31.984Z [INF] BacktestEngine:
2021-01-10T19:53:31.984Z [INF] BacktestEngine: =================================================================
2021-01-10T19:53:31.984Z [INF] BacktestEngine:  SYSTEM SPECIFICATION
2021-01-10T19:53:31.984Z [INF] BacktestEngine: =================================================================
2021-01-10T19:53:31.984Z [INF] BacktestEngine: CPU architecture: x86_64
2021-01-10T19:53:31.985Z [INF] BacktestEngine: CPU(s): 8 None
2021-01-10T19:53:31.986Z [INF] BacktestEngine: RAM-Total: 17,093 MB
2021-01-10T19:53:31.986Z [INF] BacktestEngine: RAM-Used:  14,426 MB (84.6%)
2021-01-10T19:53:31.986Z [INF] BacktestEngine: RAM-Avail: 2,625 MB (15.4%)
2021-01-10T19:53:32.011Z [INF] BacktestEngine: OS: Linux-4.4.0-18362-Microsoft-x86_64-with-glibc2.29
2021-01-10T19:53:32.011Z [INF] BacktestEngine: =================================================================
2021-01-10T19:53:32.011Z [INF] BacktestEngine:  VERSIONING
2021-01-10T19:53:32.011Z [INF] BacktestEngine: =================================================================
2021-01-10T19:53:32.011Z [INF] BacktestEngine: nautilus-trader 1.94.6
2021-01-10T19:53:32.011Z [INF] BacktestEngine: python 3.8.5
2021-01-10T19:53:32.011Z [INF] BacktestEngine: numpy 1.19.5
2021-01-10T19:53:32.011Z [INF] BacktestEngine: scipy 1.6.0
2021-01-10T19:53:32.011Z [INF] BacktestEngine: pandas 1.2.0
2021-01-10T19:53:32.011Z [INF] BacktestEngine: =================================================================
2021-01-10T19:53:32.011Z [INF] BacktestEngine: Building engine...
2021-01-10T19:53:32.011Z [INF] BypassExecutionDatabase: Initialized.
2021-01-10T19:53:32.011Z [INF] DataEngine: state=INITIALIZED...
2021-01-10T19:53:32.011Z [INF] DataCache: Initialized.
2021-01-10T19:53:32.011Z [INF] DataEngine: use_previous_close=False
2021-01-10T19:53:32.011Z [INF] BacktestDataProducer: Preparing BTC/USDT.BINANCE data...
2021-01-10T19:53:32.011Z [INF] BacktestDataProducer: Prepared 2,325,039 BTC/USDT.BINANCE quote tick rows in 7.63s.
2021-01-10T19:53:32.011Z [INF] BacktestDataProducer: Prepared 7,803,194 BTC/USDT.BINANCE trade tick rows in 17.26s.
2021-01-10T19:53:32.011Z [INF] BacktestDataProducer: Merging tick data streams...
Traceback (most recent call last):
  File "./examples/backtest/backtest_btcusdt_trade_ticks.py", line 65, in <module>
    engine = BacktestEngine(
  File "nautilus_trader/backtest/engine.pyx", line 220, in nautilus_trader.backtest.engine.BacktestEngine.__init__
    self._data_producer = BacktestDataProducer(
  File "nautilus_trader/backtest/data_producer.pyx", line 170, in nautilus_trader.backtest.data_producer.BacktestDataProducer.__init__
    self.min_timestamp = max(self._quote_tick_data.index, self._trade_tick_data.index)
  File "/home/deploy/.cache/pypoetry/virtualenvs/nautilus-trader-keG6LY4b-py3.8/lib/python3.8/site-packages/pandas/core/indexes/extension.py", line 134, in wrapper
    return op(other)
  File "/home/deploy/.cache/pypoetry/virtualenvs/nautilus-trader-keG6LY4b-py3.8/lib/python3.8/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/home/deploy/.cache/pypoetry/virtualenvs/nautilus-trader-keG6LY4b-py3.8/lib/python3.8/site-packages/pandas/core/arraylike.py", line 45, in __gt__
    return self._cmp_method(other, operator.gt)
  File "/home/deploy/.cache/pypoetry/virtualenvs/nautilus-trader-keG6LY4b-py3.8/lib/python3.8/site-packages/pandas/core/arrays/datetimelike.py", line 932, in _cmp_method
    other = self._validate_comparison_value(other)
  File "/home/deploy/.cache/pypoetry/virtualenvs/nautilus-trader-keG6LY4b-py3.8/lib/python3.8/site-packages/pandas/core/arrays/datetimelike.py", line 454, in _validate_comparison_value
    raise ValueError("Lengths must match")
ValueError: Lengths must match
```
INPUT DATA: Quotes(7,803,194 rows), Trade(2,325,039 row)

I don't think it should be like this, but there is error. 

I'm fixing this problem right now, but I'd like to ask a question to be sure. Is it correct that the backtest system can take two streams of different lengths as inputs?

**Comment by jpmediadev** [comment]
got ahead, also just discovered this issue)

**Comment by ian-wazowski** [comment]
Thanks @jpmediadev

**Comment by cjdsellers** [comment]
Yes, it should be possible for two streams to have different lengths. There's a step where these are merged into a single monotonically increasing stream.

There should only be a check that bar data for the same symbol should have equal length bid and asks.

**Comment by ian-wazowski** [comment]
> Yes, it should be possible for two streams to have different lengths. There's a step where these are merged into a single monotonically increasing stream.
> 
> There should only be a check that bar data for the same symbol should have equal length bid and asks.

I'm working on it.

**Comment by ian-wazowski** [comment]
Problem FIXED, I will request PR 9 hours latter(after sleep)

**Comment by cjdsellers** [comment]
Great work.
