### ISSUE TITLE
Reconciliation not working with trading node, interactive brokers and option on future

### ISSUE THREAD

**Issue by faysou** [nautechsystems/nautilus_trader#1789]
# Bug Report

### Expected Behavior
Existing future option positions should be reconciled without errors.

Another related question I have is how would the reconciliation work if I used databento market data, for example best bid offer, so the definition of a contract in databento and interactive brokers are compatible (IB uses CME as venue, and databento uses GLBX). For example I would want to use databento as market data provider and interactive brokers for execution.

### Actual Behavior

I get the following errors

```
2024-07-17T14:00:30.653209001Z [ERROR] TRADER-001.InteractiveBrokersInstrumentProvider: self.config.strict_symbology=False failed to parse details=IBContractDetails(contract=IBContract(secType='FOP', conId=666032021, exchange='CME', symbol='ES', localSymbol='ESU4 P5550', currency='USD', tradingClass='ES', lastTradeDateOrContractMonth='20240920', multiplier='50', strike=5550.0, right='P'), marketName='ES', minTick=0.05, orderTypes='ACTIVETIM,AD,ADJUST,ALERT,ALLOC,AVGCOST,BASKET,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,LTH,MIT,MKT,MTL,NGCOMB,NONALGO,OCA,SCALE,SCALERST,SNAPMID,SNAPMKT,SNAPREL,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,VOLAT,WHATIF', validExchanges='CME', priceMagnifier=1, underConId=568550526, longName='E-mini S&P 500', contractMonth='202409', timeZoneId='US/Central', tradingHours='20240716:1700-20240717:1600;20240717:1700-20240718:1600;20240718:1700-20240719:1600;20240720:CLOSED;20240721:1700-20240722:1600;20240722:1700-20240723:1600', liquidHours='20240717:0830-20240717:1600;20240718:0830-20240718:1600;20240719:0830-20240719:1600;20240720:CLOSED;20240721:CLOSED;20240722:0830-20240722:1600;20240722:1700-20240723:1600', aggGroup=2147483647, underSymbol='ESU4', underSecType='FUT', marketRuleIds='3541', realExpirationDate='20240920', lastTradeTime='08:30:00', minSize=Decimal('1'), sizeIncrement=Decimal('1'), suggestedSizeIncrement=Decimal('1')), Unknown security_type='FOP'
2024-07-17T14:00:30.654066001Z [ERROR] TRADER-001.ExecClient-IB: Cannot reconcile execution state
TypeError(The 'instrument_id' argument was None)
Traceback (most recent call last):
  File "/Users/ata/code/nautilus/nautilus_trader/nautilus_trader/live/execution_client.py", line 467, in generate_mass_status
    reports = await asyncio.gather(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ata/code/nautilus/nautilus_trader/nautilus_trader/adapters/interactive_brokers/execution.py", line 386, in generate_order_status_reports
    instrument = await self.instrument_provider.find_with_contract_id(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ata/code/nautilus/nautilus_trader/nautilus_trader/adapters/interactive_brokers/providers.py", line 312, in find_with_contract_id
    instrument = self.find(instrument_id)
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ata/code/nautilus/nautilus_trader/nautilus_trader/common/providers.py", line 353, in find
    PyCondition.not_none(instrument_id, "instrument_id")
  File "nautilus_trader/core/correctness.pyx", line 895, in nautilus_trader.core.correctness.PyCondition.not_none
  File "nautilus_trader/core/correctness.pyx", line 145, in nautilus_trader.core.correctness.Condition.not_none

Task exception was never retrieved
future: <Task finished name='Task-5' coro=<TradingNode.run_async() done, defined at /Users/ata/code/nautilus/nautilus_trader/nautilus_trader/live/node.py:278> exception=AttributeError("'NoneType' object has no attribute 'venue'")>
Traceback (most recent call last):
  File "/Users/ata/code/nautilus/nautilus_trader/nautilus_trader/live/node.py", line 290, in run_async
    await self.kernel.start_async()
  File "/Users/ata/code/nautilus/nautilus_trader/nautilus_trader/system/kernel.py", line 859, in start_async
    if not await self._await_execution_reconciliation():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ata/code/nautilus/nautilus_trader/nautilus_trader/system/kernel.py", line 1080, in _await_execution_reconciliation
    if not await self._exec_engine.reconcile_state(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ata/code/nautilus/nautilus_trader/nautilus_trader/live/execution_engine.py", line 477, in reconcile_state
    result = self._reconcile_mass_status(mass_status)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ata/code/nautilus/nautilus_trader/nautilus_trader/live/execution_engine.py", line 543, in _reconcile_mass_status
    f"Reconciling ExecutionMassStatus for {mass_status.venue}",
                                           ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'venue'
```

### Steps to Reproduce the Problem

1. Open a future option position on ES in an interactive brokers paper account
2. Define and run a node (the reconciliation happens by default).

```
from nautilus_trader.adapters.interactive_brokers.config import InteractiveBrokersExecClientConfig
from nautilus_trader.adapters.interactive_brokers.factories import InteractiveBrokersLiveExecClientFactory
from nautilus_trader.live.node import TradingNode
from nautilus_trader.config import TradingNodeConfig

config_node = TradingNodeConfig(
    exec_clients={
        "IB": InteractiveBrokersExecClientConfig(
            ibg_port=7497,
            account_id="DU11111111", #use a valid account here
        ),
    }
)

node = TradingNode(config=config_node)
node.add_exec_client_factory("IB", InteractiveBrokersLiveExecClientFactory)

node.build()
node.run()
```

### Specifications

- OS platform: macos
- Python version: 3.12.4
- `nautilus_trader` version: latest of develop branch

**Comment by cjdsellers** [comment]
Hi @faysou

Thanks for the report.

I believe there were some plans to provide the necessary venue mapping in the IB adapter for GLBX -> CME. @rsmb7z might be able to comment further on that.

As for the reconciliation, I can see the bug and should be an easy fix. The capability you're after here should be possible.

**Comment by rsmb7z** [comment]
> I believe there were some plans to provide the necessary venue mapping in the IB adapter for GLBX -> CME. @rsmb7z might be able to comment further on that.

Hi @faysou,
Yes, there is indeed a plan which will make things easier, as IB is definitely not a great option for high granularity data. I have created a separate tracking issue, #1790, to ensure this is not forgotten.

**Comment by faysou** [comment]
Thank you both. I'm in the process of developing a strategy using future options, databento and IB, so I find things missing I need while doing it. This can lead to some improvements for other people in the future as well. Thank you again for your quick replies.

**Comment by cjdsellers** [comment]
Hi all,

So there were two bugs here and an enhancement necessary:
- Fixed handling of when execution mass status is None ba2b932024e471994b61fb951d0abf76c9619872
- Fixed handling of when an instrument is not found 118faba5c15b7723a3d77e337a18b732e8568890

Closing this and we can continue discussions in https://github.com/nautechsystems/nautilus_trader/issues/1790.

Thanks again for the report @faysou :pray:.

**Comment by faysou** [comment]
Thank you @cjdsellers .

I think there are few lines to change still:

I would replace this line:
https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/adapters/interactive_brokers/providers.py#L232
with:
`secType=("FOP" if underlying.secType == "FUT" else "OPT"),`

This line:
https://github.com/nautechsystems/nautilus_trader/blob/develop/nautilus_trader/adapters/interactive_brokers/parsing/instruments.py#L154
with:
`elif security_type in ("OPT", "FOP"):`

Also maybe some tests should be added for FOP. To find the above I searched "OPT" in the code base.

**Comment by rsmb7z** [comment]
@faysou, thanks for the report. This has been fixed in #1789.

**Comment by faysou** [comment]
Actually what I wrote today wasn't in the fix, that's why I wrote it.

**Comment by rsmb7z** [comment]
> Actually what I wrote today wasn't in the fix, that's why I wrote it. You can click on the links to see what I mean.

This has been pushed in previous message, so it will update in `develop` branch after merge.

**Comment by faysou** [comment]
Aaah ok, sorry, thank you
