### ISSUE TITLE
Add requests module as dependency

### ISSUE THREAD

**Issue by Tapanhaz** [nautechsystems/nautilus_trader#2070]
# Bug Report

```
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Python\Environments\nautilus\Lib\site-packages\fsspec\implementations\github.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\python\I\test_nautilus\ema_cross.py", line 70, in <module>
    provider = TestDataProvider()
               ^^^^^^^^^^^^^^^^^^
  File "D:\Python\Environments\nautilus\Lib\site-packages\nautilus_trader\test_kit\providers.py", line 796, in __init__
    self._determine_filesystem()
  File "D:\Python\Environments\nautilus\Lib\site-packages\nautilus_trader\test_kit\providers.py", line 818, in _determine_filesystem
    self.fs = fsspec.filesystem("github", org="nautechsystems", repo="nautilus_trader")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Environments\nautilus\Lib\site-packages\fsspec\registry.py", line 302, in filesystem
    cls = get_filesystem_class(protocol)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Python\Environments\nautilus\Lib\site-packages\fsspec\registry.py", line 244, in get_filesystem_class
    raise ImportError(bit["err"]) from e
ImportError: Install the requests package to use the github FS
```

### Steps to Reproduce the Problem

1.  Run examples/backtest/crypto_ema_cross_ethusdt_trade_ticks.py

### Specifications

- OS platform: Windows 11 
- Python version: 3.12.7
- `nautilus_trader` version:  1.206.0

**Comment by cjdsellers** [comment]
Hi @Tapanhaz 

Thanks for the report.

We'd prefer not to add `requests` as a dependency, and can leverage our own built-in HTTP client. We'll address this soon.

**Comment by cjdsellers** [comment]
Hi @Tapanhaz

Looking into this further, `requests` seems to be required by `fsspec` to use the github FS per the error.
So I've [added](d0533f6051f45e2f0f4d51714fdbdb51c180235a) `requests` as a dev dependency since it's only required by the provider in the `test_kit`.

You can install dev dependencies with `poetry install --with dev --all-extras` (or extras as required).

Closing this as fixed, and thanks again!
