### ISSUE TITLE
Binance  ccxt live error

### ISSUE THREAD

**Issue by hongguangguo** [nautechsystems/nautilus_trader#339]
this is log, also I use ccxt verbose.

```
2021-06-03T13:02:16.200210Z [DBG] TESTER-001.RiskEngine: <--[CMD] SubmitOrder(BUY 0.007 ETH/USDT.BINANCE LIMIT @ 2836.62 GTC, trader_id=TESTER-001, strategy_id=Man-man, instrument_id=ETH/USDT.BINANCE, client_order_id=O-20210603-130216-001-man-22, strategy_id=Man-man, command_id=bb3c5317-27be-8c8d-1c1c-7fe2005d02bf).
2021-06-03T13:02:16.200228Z [DBG] TESTER-001.ExecCache: Added Order(id=O-20210603-130216-001-man-22).
2021-06-03T13:02:16.200261Z [DBG] TESTER-001.RiskEngine: <--[EVT] PositionChanged(LONG 0.071 ETH/USDT.BINANCE, account_id=BINANCE-grid_account, position_id=P-20210603-130118-001-man-1, strategy_id=Man-man, entry=BUY, avg_px_open=2835.586666666666666666666667, realized_points=3.873333333333333333333333, realized_return=0.137%, realized_pnl=-0.06533221 USDT, LONG 0.071 ETH/USDT.BINANCE, event_id=213896a4-f019-f843-cede-4fad29fe3ade).
2021-06-03T13:02:16.203897Z [DBG] TESTER-001.ExecEngine: <--[CMD] SubmitOrder(BUY 0.007 ETH/USDT.BINANCE LIMIT @ 2836.62 GTC, trader_id=TESTER-001, strategy_id=Man-man, instrument_id=ETH/USDT.BINANCE, client_order_id=O-20210603-130216-001-man-22, strategy_id=Man-man, command_id=bb3c5317-27be-8c8d-1c1c-7fe2005d02bf).
2021-06-03T13:02:16.205808Z [DBG] TESTER-001.CCXTExecClient-BINANCE: Submitted LimitOrder(BUY 0.007 ETH/USDT.BINANCE LIMIT @ 2836.62 GTC, state=INITIALIZED, client_order_id=O-20210603-130216-001-man-22).
2021-06-03T13:02:16.207547Z [DBG] TESTER-001.ExecEngine: <--[EVT] OrderSubmitted(account_id=BINANCE-grid_account, client_order_id=O-20210603-130216-001-man-22, event_id=757008cd-3758-bb0f-478e-083d28d1f50b).
2021-06-03T13:02:16.207582Z [INF] TESTER-001.Man-man: <--[EVT] OrderSubmitted(account_id=BINANCE-grid_account, client_order_id=O-20210603-130216-001-man-22, event_id=757008cd-3758-bb0f-478e-083d28d1f50b).
2021-06-03T13:02:16.207693Z [DBG] TESTER-001.RiskEngine: <--[EVT] OrderSubmitted(account_id=BINANCE-grid_account, client_order_id=O-20210603-130216-001-man-22, event_id=757008cd-3758-bb0f-478e-083d28d1f50b).

Request: POST https://fapi.binance.com/fapi/v1/order {'X-MBX-APIKEY': 'wIzIHmx8nswe1v99EtAbumGx6zZFBBnVSZQKreQXreXbNYZnaWx3Wxu5z7LaTUiE', 'Content-Type': 'application/x-www-form-urlencoded', 'User-Agent': 'python-requests/2.25.1', 'Accept-Encoding': 'gzip, deflate'} timestamp=1622725336210&recvWindow=10000&symbol=ETHUSDT&type=LIMIT&side=BUY&newClientOrderId=O-20210603-130216-001-man-22&newOrderRespType=RESULT&quantity=0.007&price=2836.62&timeInForce=GTC&signature=def2614d12c86b0348876d43e4e17a4b545dec183863e932b657d65b45e59a4a

Response: POST https://fapi.binance.com/fapi/v1/order 200 {'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'keep-alive', 'Date': 'Thu, 03 Jun 2021 13:02:16 GMT', 'Server': 'Tengine', 'Vary': 'Accept-Encoding', 'X-MBX-USED-WEIGHT-1M': '0', 'X-MBX-ORDER-COUNT-10S': '0', 'X-MBX-ORDER-COUNT-1M': '1', 'x-response-time': '6ms', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS', 'Access-Control-Allow-Credentials': 'true', 'Access-Control-Allow-Headers': '*,clienttype,Content-Type,lang,x-ui-request-trace,bnc-uuid', 'Content-Security-Policy': "default-src 'self'", 'Cache-Control': 'no-cache, no-store, must-revalidate', 'Expires': '0', 'Pragma': 'no-cache', 'strict-transport-security': 'max-age=31536000; includeSubdomains', 'x-content-type-options': 'nosniff', 'x-frame-options': 'SAMEORIGIN', 'x-xss-protection': '1; mode=block', 'Content-Encoding': 'gzip', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 ccbc34c31d1270b000318b6f37ee028f.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'NRT12-C4', 'X-Amz-Cf-Id': 'UazsnpHn_EKPz_KsBrrvovu28af42dKuN7cNYW48UVsmpUdAupFW-w=='} {"orderId":8389765499231765791,"symbol":"ETHUSDT","status":"NEW","clientOrderId":"O-20210603-130216-001-man-22","price":"2836.62","avgPrice":"0.00000","origQty":"0.007","executedQty":"0","cumQty":"0","cumQuote":"0","timeInForce":"GTC","type":"LIMIT","reduceOnly":false,"closePosition":false,"side":"BUY","positionSide":"BOTH","stopPrice":"0","workingType":"CONTRACT_PRICE","priceProtect":false,"origType":"LIMIT","updateTime":1622725336529}
2021-06-03T13:02:16.579Z message {"e":"ORDER_TRADE_UPDATE","T":1622725336529,"E":1622725336533,"o":{"s":"ETHUSDT","c":"O-20210603-130216-001-man-22","S":"BUY","o":"LIMIT","f":"GTC","q":"0.007","p":"2836.62","ap":"0","sp":"0","x":"NEW","X":"NEW","i":8389765499231765791,"l":"0","z":"0","L":"0","T":1622725336529,"t":0,"b":"217.33201","a":"179.78254","m":false,"R":false,"wt":"CONTRACT_PRICE","ot":"LIMIT","ps":"BOTH","cp":false,"rp":"0","pP":false,"si":0,"ss":0}}
2021-06-03T13:02:24.864Z ping WSMessage(type=<WSMsgType.PING: 9>, data=bytearray(b'1622725344823'), extra='')
2021-06-03T13:02:39.255Z message {"e":"ACCOUNT_UPDATE","T":1622725359197,"E":1622725359204,"a":{"B":[{"a":"USDT","wb":"742.03448108","cw":"742.03448108","bc":"0"}],"P":[{"s":"ETHUSDT","pa":"0.078","ep":"2835.67940","cr":"0.51155333","up":"0.22608504","mt":"cross","iw":"0","ps":"BOTH","ma":"USDT"},{"s":"ETHUSDT","pa":"0","ep":"0.00000","cr":"0.03355000","up":"0","mt":"cross","iw":"0","ps":"LONG","ma":"USDT"},{"s":"ETHUSDT","pa":"0","ep":"0.00000","cr":"-0.26003999","up":"0","mt":"cross","iw":"0","ps":"SHORT","ma":"USDT"}],"m":"ORDER"}}
2021-06-03T13:02:39.256Z message {"e":"ORDER_TRADE_UPDATE","T":1622725359197,"E":1622725359204,"o":{"s":"ETHUSDT","c":"O-20210603-130216-001-man-22","S":"BUY","o":"LIMIT","f":"GTC","q":"0.007","p":"2836.62","ap":"2836.62000","sp":"0","x":"TRADE","X":"FILLED","i":8389765499231765791,"l":"0.007","z":"0.007","L":"2836.62","n":"0.00397126","N":"USDT","T":1622725359197,"t":680819153,"b":"197.47567","a":"179.78254","m":true,"R":false,"wt":"CONTRACT_PRICE","ot":"LIMIT","ps":"BOTH","cp":false,"rp":"0","pP":false,"si":0,"ss":0}}
```

**`2021-06-03T13:02:39.257403Z [ERR] TESTER-001.CCXTExecClient-BINANCE: Cannot fill un-cached order with VenueOrderId('8389765499231765791').`**

**Comment by cjdsellers** [comment]
Did you by any chance submit that order from a web / mobile app or by some other means?

Normally this occurs when an order was not initialized within the running NautilusTrader instance.

**Comment by hongguangguo** [comment]
`2021-06-03T13:02:16.200228Z [DBG] TESTER-001.ExecCache: Added Order(id=O-20210603-130216-001-man-22).`
this shows  clientOrderId successfuly added in cache.

**Comment by hongguangguo** [comment]
First new ORDER_TRADE_UPDATE event occurs, but now it's not added in cache by VenueOrderId, while  filled ORDER_TRADE_UPDATE event occurs, so the error happened. 
This's my guess.

**Comment by cjdsellers** [comment]
I just did a search for `Cannot fill un-cached order`.
4 references found all in `ccxt/execution.pyx`, that additional 'hot-cache' exists due to some limitations with the availability of client order identifiers coming off CCXT messages.

You may have uncovered an edge case here, I'm not certain at this stage why the order wouldn't have been in that cache.

**Comment by hongguangguo** [comment]
previously `_watch_orders `happened error. So submitted order will not update.

this log show why `_watch_orders `  error, `timestamp is None`

>this is event[0] value 
 {'info': {'s': 'ETHUSDT', 'c': 'O-20210604-065009-001-man-13', 'S': 'SELL', 'o': 'LIMIT', 'f': 'GTC', 'q': '0.004', 'p': '2626.84', 'ap': '2626.84000', 'sp': '0', 'x': 'TRADE', 'X': 'FILLED', 'i': 8389765499296095330, 'l': '0.004', 'z': '0.004', 'L': '2626.84', 'n': '0.00210147', 'N': 'USDT', 'T': 1622789417899, 't': 683885195, 'b': '114.77552', 'a': '10.51783', 'm': True, 'R': False, 'wt': 'CONTRACT_PRICE', 'ot': 'LIMIT', 'ps': 'BOTH', 'cp': False, 'rp': '0.03044000', 'pP': False, 'si': 0, 'ss': 0}, 'symbol': 'ETH/USDT', 'id': '8389765499296095330', 'clientOrderId': 'O-20210604-065009-001-man-13', 'timestamp': None, 'datetime': None, 'lastTradeTimestamp': 1622789417899, 'type': 'limit', 'timeInForce': 'GTC', 'postOnly': None, 'side': 'sell', 'price': 2626.84, 'stopPrice': 0.0, 'amount': 0.004, 'cost': 10.50736, 'average': 2626.84, 'filled': 0.004, 'remaining': 0.0, 'status': 'closed', 'fee': {'cost': 0.00210147, 'currency': 'USDT'}, 'trades': None}

```
2021-06-04T06:50:17.957803Z [ERR] TESTER-001.CCXTExecClient-BINANCE: TypeError(an integer is required)
 Traceback (most recent call last):
  File "nautilus_trader/adapters/ccxt/execution.pyx", line 497, in nautilus_trader.adapters.ccxt.execution.CCXTExecutionClient._watch_orders
  File "nautilus_trader/adapters/ccxt/execution.pyx", line 656, in nautilus_trader.adapters.ccxt.execution.CCXTExecutionClient._on_order_status
```
so I fix it

```
        if event['timestamp'] is not None:
            timestamp_ns = <int64_t>(event["timestamp"])
        else:
            timestamp_ns = <int64_t>(event["lastTradeTimestamp"])

```

**Comment by cjdsellers** [comment]
Well done, would you like to submit a PR for it?

Alternatively I can apply the fix myself, up to you.

**Comment by hongguangguo** [comment]
I would like to submit a PR ,and I have some other idea that's not done. I submit this first.
