### ISSUE TITLE
Build wheel error PEP 517

### ISSUE THREAD

**Issue by crazy25000** [nautechsystems/nautilus_trader#362]
Pulled in master and tried to build, but getting this error. Is anyone else able to reproduce it? I also tried below with Cython `3.0a7` and `3.0a8`. I also tried with a new Python 3.9.1 virtual env.

Note: `3.0a6` is in the README and is probably outdated, but tried it anyways.

```bash
pip install -U Cython==3.0a6
git clone https://github.com/nautechsystems/nautilus_trader
cd nautilus_trader
pip install .
```

```bash
  Building wheel for nautilus-trader (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/.pyenv/versions/3.8.7/envs/at-3.8.7/bin/python3.8 /home/user/.pyenv/versions/3.8.7/envs/at-3.8.7/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpn_9g8ohr
       cwd: /tmp/pip-req-build-aac2hd43
  Complete output (39 lines):
  DEBUG_MODE=False, PROFILING_MODE=False, ANNOTATION_MODE=False,
  
  Starting build...
  System: Linux 64-bit
  Python: 3.8.7
  Cython: 3.0.0a8
  NumPy:  1.21.0
  Traceback (most recent call last):
    File "build.py", line 178, in <module>
      build({})
    File "build.py", line 137, in build
      extensions = _build_extensions()
    File "build.py", line 69, in _build_extensions
      if LooseVersion("3.0a7") <= LooseVersion(cython_compiler_version):
    File "/home/user/.pyenv/versions/3.8.7/lib/python3.8/distutils/version.py", line 58, in __le__
      c = self._cmp(other)
    File "/home/user/.pyenv/versions/3.8.7/lib/python3.8/distutils/version.py", line 337, in _cmp
      if self.version < other.version:
  TypeError: '<' not supported between instances of 'str' and 'int'
  Traceback (most recent call last):
    File "/home/user/.pyenv/versions/3.8.7/envs/at-3.8.7/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
      main()
    File "/home/user/.pyenv/versions/3.8.7/envs/at-3.8.7/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/user/.pyenv/versions/3.8.7/envs/at-3.8.7/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-bqj20cr6/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 68, in build_wheel
      return unicode(WheelBuilder.make_in(poetry, Path(wheel_directory)))
    File "/tmp/pip-build-env-bqj20cr6/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 72, in make_in
      wb.build()
    File "/tmp/pip-build-env-bqj20cr6/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 99, in build
      self._build(zip_file)
    File "/tmp/pip-build-env-bqj20cr6/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 125, in _build
      self._run_build_script(self._package.build_script)
    File "/tmp/pip-build-env-bqj20cr6/overlay/lib/python3.8/site-packages/poetry/core/masonry/builders/wheel.py", line 175, in _run_build_script
      subprocess.check_call([self.executable.as_posix(), build_script])
    File "/home/user/.pyenv/versions/3.8.7/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/home/user/.pyenv/versions/3.8.7/envs/at-3.8.7/bin/python3.8', 'build.py']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for nautilus-trader
Failed to build nautilus-trader
```

**Comment by cjdsellers** [comment]
This was discovered when upgrading to Cython 3.0.0a8.

The import of and call to `LooseVersion` has been removed on the latest `develop` branch. It's no longer required as we're now specifying the specific version of Cython we support in the `pyproject.toml`:
```
[build-system]
requires = [
    "setuptools",
    "poetry-core>=1.0.3",
    "numpy>=1.21.0",
    "Cython>=3.0.0a8",
]
```

If you rebase/merge the latest `develop` then this should fix the above for you.

**Comment by crazy25000** [comment]
@cjdsellers ah I see, yeah that fixed it, thanks for the reply!
