### ISSUE TITLE
Improve error handling on negative account balances in backtest

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#545]
When running a backtest, if an account runs out of cash, the error nautilus currently raises is a little cryptic even for someone familiar with the code. For someone new to the platform, this could be very confusing. 

```
Traceback (most recent call last):
  ... 
  File "nautilus_trader/backtest/engine.pyx", line 795, in nautilus_trader.backtest.engine.BacktestEngine.run_streaming
  File "nautilus_trader/backtest/engine.pyx", line 915, in nautilus_trader.backtest.engine.BacktestEngine._run
  File "nautilus_trader/backtest/exchange.pyx", line 644, in nautilus_trader.backtest.exchange.SimulatedExchange.process
  File "nautilus_trader/backtest/exchange.pyx", line 776, in nautilus_trader.backtest.exchange.SimulatedExchange._process_order
  File "nautilus_trader/backtest/exchange.pyx", line 796, in nautilus_trader.backtest.exchange.SimulatedExchange._process_market_order
  File "nautilus_trader/backtest/exchange.pyx", line 1268, in nautilus_trader.backtest.exchange.SimulatedExchange._fill_market_order
  File "nautilus_trader/backtest/exchange.pyx", line 1318, in nautilus_trader.backtest.exchange.SimulatedExchange._apply_fills
  File "nautilus_trader/backtest/exchange.pyx", line 1370, in nautilus_trader.backtest.exchange.SimulatedExchange._fill_order
  File "nautilus_trader/backtest/exchange.pyx", line 1643, in nautilus_trader.backtest.exchange.SimulatedExchange._generate_order_filled
  File "nautilus_trader/execution/client.pyx", line 773, in nautilus_trader.execution.client.ExecutionClient.generate_order_filled
  File "nautilus_trader/execution/client.pyx", line 784, in nautilus_trader.execution.client.ExecutionClient._send_order_event
  File "nautilus_trader/msgbus/bus.pyx", line 240, in nautilus_trader.msgbus.bus.MessageBus.send
  File "nautilus_trader/execution/engine.pyx", line 438, in nautilus_trader.execution.engine.ExecutionEngine.process
  File "nautilus_trader/execution/engine.pyx", line 450, in nautilus_trader.execution.engine.ExecutionEngine.process
  File "nautilus_trader/execution/engine.pyx", line 604, in nautilus_trader.execution.engine.ExecutionEngine._handle_event
  File "nautilus_trader/msgbus/bus.pyx", line 449, in nautilus_trader.msgbus.bus.MessageBus.publish_c
  File "nautilus_trader/portfolio/portfolio.pyx", line 356, in nautilus_trader.portfolio.portfolio.Portfolio.update_order
  File "nautilus_trader/portfolio/portfolio.pyx", line 406, in nautilus_trader.portfolio.portfolio.Portfolio.update_order
  File "nautilus_trader/accounting/manager.pyx", line 112, in nautilus_trader.accounting.manager.AccountsManager.update_balances
  File "nautilus_trader/accounting/manager.pyx", line 457, in nautilus_trader.accounting.manager.AccountsManager._update_balance_single_currency
  File "nautilus_trader/model/objects.pyx", line 559, in nautilus_trader.model.objects.AccountBalance.__init__
  File "nautilus_trader/core/correctness.pyx", line 654, in nautilus_trader.core.correctness.Condition.not_negative
ValueError: The 'total' was not greater than or equal to zero (>= 0), was -160591.2
```

I think theres a couple of things we could do to improve this:
- We should catch this error somewhere in the sim exchange and raise a proper `AccountBalanaceNegative` exception if it happens.
- We could potentially catch orders in the Risk Engine that would result in a negative balance and reject?
- We could also possibly throw some warnings if the account balance falls below some configurable threshold? This would at least allow someone to look at the logs and see something like `LOW ACCOUNT BALANCE <10%` before some exception was raised, to get more idea of what their backtest / strategy is doing.

**Comment by cjdsellers** [comment]
I agree, this could be handled much better.

The general `ValueError` being raised from the `AccountBalance` is far too low-level.

I think the solution is in two parts:

- 1. Raise an `AccountBalanceNegative` error from the `AccountManager` if it would update a free balance which becomes negative. This offers a user more context about that the problem actually is.
- 2. The platform shouldn't actually allow this, as either an exchange wouldn't allow an order to be submitted requiring collateral exceeding the account balance / margin (at least on a best effort basis) or it should be caught in the `RiskEngine`.

Part 1 is fairly straight forward.
Part 2, I think one consideration is any preemptive calculation should only occur once (for performance reasons), and I feel this is a useful calculation for the `RiskEngine`, as the value could be used for other pre-trade risk checks and warnings.

So I propose we start preemptively calculating possible account equity and margins at the `RiskEngine`, and deny order which would exceed configurable limits.

I also like your idea of the low balance warning, which could also be generated around this area of logic.

Thoughts?

**Comment by cjdsellers** [comment]
My last push to the `develop` branch implements part 1 (`AccountBalanceNegative` exceptions).

For part 2, I've made some headway with re-wiring the logic in the `RiskEngine` for pre-trade risk checks. It still needs some more work though, particularly in recovering the applicable account from the cache, and a reliable performant way to do that.

**Comment by limx0** [comment]
Yep this sounds great. Agreed on the performance considerations - hopefully we can get away with one check on order submit?

**Comment by TheRealBecks** [comment]
I got this error when backtesting:
```
2019-01-15T11:02:00.000000000Z [INF] BACKTESTER-001.EMACross-000: <--[EVT] OrderSubmitted(account_id=NYSE-001, instrument_id=AMD.NYSE, client_order_id=O-20190115-110200-001-000-957, ts_event=1547550120000000000).
distributed.worker - WARNING - Compute Failed
Function:  execute_task
args:      ((<function apply at 0x7f0b3fd341f0>, <function BacktestNode._run_delayed at 0x7f0b042d8e50>, [<nautilus_trader.backtest.node.BacktestNode object at 0x7f0b042fd730>], (<class 'dict'>, [['run_config_id', 'b9734cf578d13b2dfa3261d334bd6cae'], ['engine_config', BacktestEngineConfig(trader_id='BACKTESTER-001', log_level='INFO', cache=None, cache_database=None, data_engine=None, risk_engine=RiskEngineConfig(bypass=True, max_order_rate='100/00:00:01', max_notional_per_order={}), exec_engine=None, bypass_logging=False, run_analysis=True)], ['venue_configs', [(<function apply at 0x7f0b3fd341f0>, <class 'nautilus_trader.backtest.config.BacktestVenueConfig'>, (), (<class 'dict'>, [['name', 'NYSE'], ['oms_type', 'HEDGING'], ['account_type', 'MARGIN'], ['base_currency', 'USD'], ['starting_balances', ['100000 USD']], ['book_type', 'L1_TBBO'], ['routing', False]]))]], ['data_configs', [(<function apply at 0x7f0b3fd341f0>, <class 'nautilus_trader.backtest.config.BacktestDataConfig'>, (), (<class 'dict
kwargs:    {}
Exception: 'AccountBalanceNegative()'

Traceback (most recent call last):
  File "/home/becks/Entwicklung/nautilus_strategies/nautilus_strategies/nautilus4.py", line 106, in <module>
    main()
  File "/home/becks/Entwicklung/nautilus_strategies/nautilus_strategies/nautilus4.py", line 101, in main
    results = task.compute()
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib/python3.8/site-packages/dask/base.py", line 288, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib/python3.8/site-packages/dask/base.py", line 571, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib/python3.8/site-packages/distributed/client.py", line 2746, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib/python3.8/site-packages/distributed/client.py", line 1946, in gather
    return self.sync(
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib/python3.8/site-packages/distributed/utils.py", line 310, in sync
    return sync(
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib/python3.8/site-packages/distributed/utils.py", line 364, in sync
    raise exc.with_traceback(tb)
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib/python3.8/site-packages/distributed/utils.py", line 349, in f
    result[0] = yield future
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib64/python3.8/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib/python3.8/site-packages/distributed/client.py", line 1811, in _gather
    raise exception.with_traceback(traceback)
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib/python3.8/site-packages/dask/utils.py", line 39, in apply
    return func(*args, **kwargs)
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/src/nautilus-trader/nautilus_trader/backtest/node.py", line 147, in _run_delayed
    return self._run(
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/src/nautilus-trader/nautilus_trader/backtest/node.py", line 219, in _run
    backtest_runner(
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/src/nautilus-trader/nautilus_trader/backtest/node.py", line 319, in backtest_runner
    return engine.run(run_config_id=run_config_id)
  File "nautilus_trader/backtest/engine.pyx", line 748, in nautilus_trader.backtest.engine.BacktestEngine.run
  File "nautilus_trader/backtest/engine.pyx", line 911, in nautilus_trader.backtest.engine.BacktestEngine._run
  File "nautilus_trader/backtest/exchange.pyx", line 777, in nautilus_trader.backtest.exchange.SimulatedExchange.process
  File "nautilus_trader/backtest/exchange.pyx", line 911, in nautilus_trader.backtest.exchange.SimulatedExchange._process_order
  File "nautilus_trader/backtest/exchange.pyx", line 931, in nautilus_trader.backtest.exchange.SimulatedExchange._process_market_order
  File "nautilus_trader/backtest/exchange.pyx", line 1415, in nautilus_trader.backtest.exchange.SimulatedExchange._fill_market_order
  File "nautilus_trader/backtest/exchange.pyx", line 1465, in nautilus_trader.backtest.exchange.SimulatedExchange._apply_fills
  File "nautilus_trader/backtest/exchange.pyx", line 1517, in nautilus_trader.backtest.exchange.SimulatedExchange._fill_order
  File "nautilus_trader/backtest/exchange.pyx", line 1795, in nautilus_trader.backtest.exchange.SimulatedExchange._generate_order_filled
  File "nautilus_trader/execution/client.pyx", line 777, in nautilus_trader.execution.client.ExecutionClient.generate_order_filled
  File "nautilus_trader/execution/client.pyx", line 788, in nautilus_trader.execution.client.ExecutionClient._send_order_event
  File "nautilus_trader/msgbus/bus.pyx", line 240, in nautilus_trader.msgbus.bus.MessageBus.send
  File "nautilus_trader/execution/engine.pyx", line 440, in nautilus_trader.execution.engine.ExecutionEngine.process
  File "nautilus_trader/execution/engine.pyx", line 452, in nautilus_trader.execution.engine.ExecutionEngine.process
  File "nautilus_trader/execution/engine.pyx", line 590, in nautilus_trader.execution.engine.ExecutionEngine._handle_event
  File "nautilus_trader/execution/engine.pyx", line 611, in nautilus_trader.execution.engine.ExecutionEngine._apply_event_to_order
  File "nautilus_trader/msgbus/bus.pyx", line 449, in nautilus_trader.msgbus.bus.MessageBus.publish_c
  File "nautilus_trader/portfolio/portfolio.pyx", line 356, in nautilus_trader.portfolio.portfolio.Portfolio.update_order
  File "nautilus_trader/portfolio/portfolio.pyx", line 406, in nautilus_trader.portfolio.portfolio.Portfolio.update_order
  File "nautilus_trader/accounting/manager.pyx", line 120, in nautilus_trader.accounting.manager.AccountsManager.update_balances
  File "nautilus_trader/accounting/manager.pyx", line 491, in nautilus_trader.accounting.manager.AccountsManager._update_balance_single_currency
Exception: AccountBalanceNegative()
distributed.nanny - WARNING - Worker process still alive after 3 seconds, killing
```
Seems to be related or exactly the issue you're working on?

**Comment by cjdsellers** [comment]
The `RiskEngine` pre-trade risk checks now include checks for order notional value vs free balance, as well as cumulative notional per side for order lists.

**Comment by cjdsellers** [comment]
I was working to add an order validation check at the exchange itself, however it was becoming complex with currency conversions necessary for accounts with a single base currency. Leaving this issue open as there still may be another solution layer at the `SimulatedExchange` which can be implemented.

**Comment by cjdsellers** [comment]
Two accounting scenarios are now better handled during a backtest (rather than being unhandled exceptions) providing more description, and will end the backtest with the normal flow so that reports can be generated for post-run analysis.

When account balance for a currency becomes negative:
```
2020-08-14T10:22:37.073999872Z [ERR] BACKTESTER-001.BacktestEngine: Stopping backtest from AccountBalanceNegative(balance=-0.61637284, currency=USDT).
2020-08-14T10:22:37.073999872Z [INF] BACKTESTER-001.BACKTESTER-001: STOPPING...

```

When account margin for a currency is exceeded:
```
2020-01-30T15:47:27.213999872Z [INF] BACKTESTER-001.Portfolio: AUD/USD.SIM net_position=-1000000.0
2020-01-30T15:47:27.213999872Z [ERR] BACKTESTER-001.BacktestEngine: Stopping backtest from AccountMarginExceeded(balance=986.59, margin=2012.60, free=-1026.01, currency=USD).
2020-01-30T15:47:27.213999872Z [INF] BACKTESTER-001.BACKTESTER-001: STOPPING...

```

Closing for now as this will be revisited when the "accounting v2 refactor" occurs (likely a Rust port also).
