### ISSUE TITLE
catalog.bars(["NAME.EXCHANGE"]) not working

### ISSUE THREAD

**Issue by TheRealBecks** [nautechsystems/nautilus_trader#552]
I loaded my data into the catalog and tried to load that in a new script like that:
```
catalog = DataCatalog(CATALOG_PATH)
print(catalog.bars(["AMD.NYSE"]))
```

But I will get the following error:
```
Traceback (most recent call last):
  File "/home/becks/Entwicklung/nautilus_strategies/nautilus_strategies/nautilus4.py", line 32, in <module>
    print(catalog.bars(["AMD.NYSE"]))
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib64/python3.8/site-packages/nautilus_trader/persistence/catalog.py", line 324, in bars
    return self._query_subclasses(
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib64/python3.8/site-packages/nautilus_trader/persistence/catalog.py", line 251, in _query_subclasses
    raise e
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib64/python3.8/site-packages/nautilus_trader/persistence/catalog.py", line 236, in _query_subclasses
    df = self._query(
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/lib64/python3.8/site-packages/nautilus_trader/persistence/catalog.py", line 129, in _query
    table = dataset.to_table(filter=combine_filters(*filters), **(table_kwargs or {}))
  File "pyarrow/_dataset.pyx", line 491, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 466, in pyarrow._dataset.Dataset.scanner
  File "pyarrow/_dataset.pyx", line 3051, in pyarrow._dataset.Scanner.from_dataset
  File "pyarrow/_dataset.pyx", line 2915, in pyarrow._dataset._populate_builder
  File "pyarrow/_dataset.pyx", line 805, in pyarrow._dataset._bind
  File "pyarrow/error.pxi", line 143, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(instrument_id) in bar_type: dictionary<values=string, indices=int32, ordered=0>
open: string
high: string
low: string
close: string
volume: string
ts_event: int64
ts_init: int64
```

**Comment by limx0** [comment]
@cjdsellers for the bars we'll need to persist the `instrument_id` from the bar spec into parquet so they can be queried.

**Comment by limx0** [comment]
This is also likely also causing the last issue in #554

**Comment by limx0** [comment]
@TheRealBecks could you try out the develop branch and let us know if this can be closed now?

**Comment by TheRealBecks** [comment]
I can't run my current code, so I can't test it, because of this traceback:
```
Traceback (most recent call last):
  File "/home/becks/Entwicklung/nautilus_strategies/nautilus_strategies/nautilus4.py", line 7, in <module>
    from nautilus_trader.backtest.config import (
  File "/home/becks/.local/share/virtualenvs/nautilus_strategies-khFnq7GI/src/nautilus-trader/nautilus_trader/backtest/config.py", line 26, in <module>
    from nautilus_trader.cache.cache import CacheConfig
ModuleNotFoundError: No module named 'nautilus_trader.cache.cache'
```
The file is named `cache.pyx`, but here you're importing a Python module, am I right?
https://github.com/nautechsystems/nautilus_trader/blob/9cf6082f2106df36e954a8919755e69efad7a902/nautilus_trader/backtest/config.py#L26

**Comment by cjdsellers** [comment]
Could you try running `make clean build` from the top-level `nautilus_trader` directory, and they try your code again?

If there are changes to `develop` which you pull in, you normally need to recompile. Hope this helps, let me know what the outcome is or if you've already tried this.

**Comment by TheRealBecks** [comment]
I did a `make clean build` and now I'm getting the exact same error as in my initial comment.

**Comment by cjdsellers** [comment]
I just pushed a big cleanup to the config import paths to `develop`. When you get a chance could you please retry.

**Comment by TheRealBecks** [comment]
It's working now :+1:

**Comment by limx0** [comment]
Great, closing this one.
