### ISSUE TITLE
cannot resolution 15 min bars

### ISSUE THREAD

**Issue by graceyangfan** [nautechsystems/nautilus_trader#627]
https://github.com/nautechsystems/nautilus_trader/blob/1540a76bbf0b647087ef24a972dcb336aa6dd98f/nautilus_trader/adapters/binance/common/parsing/data.py#L182

when I running a multi-time bar strategy,this code cannot resolution  well.
config code:
```strat_config1 = SmallTrendConfig(
    instrument_id="ETHUSDT-PERP.BINANCE",
    bar_type1="ETHUSDT-PERP.BINANCE-1-MINUTE-LAST-EXTERNAL",
    bar_type2="ETHUSDT-PERP.BINANCE-15-MINUTE-LAST-EXTERNAL",
    period=40,
    trade_size=Decimal("0.005"),
    order_id_tag = '001'
)

the errors are:

RuntimeError(unsupported time aggregation resolution, was 5)
Traceback (most recent call last):
  File "nautilus_trader/network/websocket.pyx", line 269, in nautilus_trader.network.websocket.WebSocketClient.start
  File "/home/ubuntu/nautilus_trader/nautilus_trader/adapters/binance/futures/data.py", line 720, in _handle_ws_message
    self._handle_kline(raw)
  File "/home/ubuntu/nautilus_trader/nautilus_trader/adapters/binance/futures/data.py", line 793, in _handle_kline
    bar: BinanceBar = parse_bar_ws(
  File "/home/ubuntu/nautilus_trader/nautilus_trader/adapters/binance/common/parsing/data.py", line 195, in parse_bar_ws
    raise RuntimeError(f"unsupported time aggregation resolution, was {resolution}")```

**Comment by cjdsellers** [comment]
So for bar aggregations you have a choice of either:
- `EXTERNAL` aggregated external to the platform i.e. by Binance
- `INTERNAL` the bar has been aggregated by Nautilus from raw ticks

As you've chosen `EXTERNAL` then you can only request for those bars which Binance themselves aggregate:

```
    1m
    3m
    5m
    15m
    30m
    1h
    2h
    4h
    6h
    8h
    12h
    1d
    3d
    1w
    1M
```

You could try `INTERNAL` although I'm not sure if you have the data available or if this is backtest or live.

**Comment by cjdsellers** [comment]
I was able to subscribe, I'll check the parsing off the WebSocket when a bar finally comes back

```
2022-05-01T02:21:43.031912724Z [INF] TESTER-001.VolatilityMarketMaker-000: Received <Bar[999]> data for ETHUSDT-PERP.BINANCE-15-MINUTE-LAST-EXTERNAL.
2022-05-01T02:21:43.722963105Z [INF] TESTER-001.BinanceWebSocketClient: Connecting to wss://stream.binancefuture.com/stream?streams=ethusdt@kline_15m/ethusdt@bookTicker
```

**Comment by graceyangfan** [comment]
@cjdsellers  so if I want to use the external data,how should I correct "bar_type2="ETHUSDT-PERP.BINANCE-15-MINUTE-LAST-EXTERNAL"

**Comment by cjdsellers** [comment]
I've found a bug, I think you're subscribing correctly.

**Comment by cjdsellers** [comment]
Just putting a fix together with a test.

**Comment by cjdsellers** [comment]
We have to add monthly time aggregations to the platform to pulls support Binance, just doing that now

**Comment by cjdsellers** [comment]
Just pushed a fix to the `develop` branch.
