### ISSUE TITLE
Streaming live market data compatibility

### ISSUE THREAD

**Issue by alienbrett** [nautechsystems/nautilus_trader#644]
# Feature Request

Hi,

I'm writing a custom adapter to interface with tda-api (TDAmeritrade's python API wrapper), and I'm looking to plug in the stream client, since it offers much more data than the standard request-response endpoints.

I'm running into trouble with the async loop and task execution- it seems that after a certain point in the spinnup process, tasks aren't being executed. For a rough example, if I make the following change (inside the live data provider class, the task never executes, despite the 10 second timeout before dispose is triggered:
```python
await asyncio.sleep(0)
self._handle_data(data)

# change to the following
await asyncio.sleep(1)
self._handle_data(data)

```

Is there a way to ensure my live data client (which relies on a running asyncio loop to push new data) runs concurrently with the trading node + strategy logic? It doesn't seem like this is the case now.

Thanks in advance,
Brett

**Comment by cjdsellers** [comment]
Hi Brett,

There can be many subtitles with Python and async. I'm not sure I can give you a definitive answer to where things are going wrong based on your description and the code snippet.

Do you know if the TDAmeritrade client uses its own event loop, or are you using another event loop yourself? or the one which is passed into the live client accessed through `self._loop` ?

I've just checked some of the other `LiveDataClient` implementations, and they're calling that same method. Multiple people have been able to run trading nodes for days on end with no issue so its likely something within your class I would say.

**Comment by alienbrett** [comment]
on my TDAmeritradeMarketDataClient object, I create a separate task which instantiates the streamer in the obj.connect() method.

I've found if my task takes too long to reply (by taking too large of an asyncio.sleep(x) wait), the trading node takes over? This is all the log info I can muster


This is a "successful" run, with a small wait time:


2022-05-21T17:28:20.624889049Z [INF] TESTER-001.SubscribeStrategy-000: RUNNING.
2022-05-21T17:28:20.624911252Z [INF] TESTER-001.TESTER-001: RUNNING.
2022-05-21T17:28:20.624921396Z [INF] TESTER-001.TradingNode: RUNNING.
2022-05-21T17:28:20.625629160Z [INF] TESTER-001.DataClient-TDAMERITRADE: waking after 0.001s
2022-05-21T17:28:20.625669753Z [INF] TESTER-001.DataClient-TDAMERITRADE: Submitting data SPY.TDAMERITRADE,390.60,390.70,1,6,1653154100451000
2022-05-21T17:28:20.625686691Z [INF] TESTER-001.DataClient-TDAMERITRADE: waking after 0.001s
2022-05-21T17:28:20.625695475Z [INF] TESTER-001.DataClient-TDAMERITRADE: Submitting data QQQ.TDAMERITRADE,288.95,289.08,1,5,1653154100451000
2022-05-21T17:28:20.625702501Z [INF] TESTER-001.DataClient-TDAMERITRADE: waking after 0.001s
2022-05-21T17:28:20.625710614Z [INF] TESTER-001.DataClient-TDAMERITRADE: Submitting data IWM.TDAMERITRADE,176.22,176.49,40,2,1653154100451000
2022-05-21T17:28:20.626377103Z [INF] TESTER-001.SubscribeStrategy-000: on quote tick: SPY.TDAMERITRADE,390.60,390.70,1,6,1653154100451000
Traceback (most recent call last):
  File "nautilus_trader/common/component.pyx", line 522, in nautilus_trader.common.component.Component.dispose
  File "nautilus_trader/common/component.pyx", line 616, in nautilus_trader.common.component.Component._trigger_fsm
  File "nautilus_trader/common/component.pyx", line 613, in nautilus_trader.common.component.Component._trigger_fsm
  File "nautilus_trader/core/fsm.pyx", line 127, in nautilus_trader.core.fsm.FiniteStateMachine.trigger
nautilus_trader.core.fsm.InvalidStateTrigger: RUNNING -> DISPOSE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/vscode/appdata/nautilus_sandbox/tdameritrade_adapter_example1.py", line 105, in <module>
    node.dispose()
  File "/app/.local/lib/python3.10/site-packages/nautilus_trader/live/node.py", line 338, in dispose
    self.kernel.trader.dispose()
  File "nautilus_trader/common/component.pyx", line 502, in nautilus_trader.common.component.Component.dispose
  File "nautilus_trader/common/component.pyx", line 531, in nautilus_trader.common.component.Component.dispose
  File "nautilus_trader/common/component.pyx", line 616, in nautilus_trader.common.component.Component._trigger_fsm
  File "nautilus_trader/common/component.pyx", line 613, in nautilus_trader.common.component.Component._trigger_fsm
  File "nautilus_trader/core/fsm.pyx", line 127, in nautilus_trader.core.fsm.FiniteStateMachine.trigger
nautilus_trader.core.fsm.InvalidStateTrigger: RUNNING -> DISPOSED






And this is an "unsuccessful" run- notice the .sleep() never wakes up, and fails to log the wakeup event. In addition, the machine seems to shutdown in a different way? There are pending tasks tasks which get destroyed before they have a chance to execute



2022-05-21T17:33:40.226110560Z [INF] TESTER-001.SubscribeStrategy-000: RUNNING.
2022-05-21T17:33:40.226129827Z [INF] TESTER-001.TESTER-001: RUNNING.
2022-05-21T17:33:40.226140119Z [INF] TESTER-001.TradingNode: RUNNING.
Traceback (most recent call last):
  File "nautilus_trader/common/component.pyx", line 522, in nautilus_trader.common.component.Component.dispose
  File "nautilus_trader/common/component.pyx", line 616, in nautilus_trader.common.component.Component._trigger_fsm
  File "nautilus_trader/common/component.pyx", line 613, in nautilus_trader.common.component.Component._trigger_fsm
  File "nautilus_trader/core/fsm.pyx", line 127, in nautilus_trader.core.fsm.FiniteStateMachine.trigger
nautilus_trader.core.fsm.InvalidStateTrigger: RUNNING -> DISPOSE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/vscode/appdata/nautilus_sandbox/tdameritrade_adapter_example1.py", line 105, in <module>
    node.dispose()
  File "/app/.local/lib/python3.10/site-packages/nautilus_trader/live/node.py", line 338, in dispose
    self.kernel.trader.dispose()
  File "nautilus_trader/common/component.pyx", line 502, in nautilus_trader.common.component.Component.dispose
  File "nautilus_trader/common/component.pyx", line 531, in nautilus_trader.common.component.Component.dispose
  File "nautilus_trader/common/component.pyx", line 616, in nautilus_trader.common.component.Component._trigger_fsm
  File "nautilus_trader/common/component.pyx", line 613, in nautilus_trader.common.component.Component._trigger_fsm
  File "nautilus_trader/core/fsm.pyx", line 127, in nautilus_trader.core.fsm.FiniteStateMachine.trigger
nautilus_trader.core.fsm.InvalidStateTrigger: RUNNING -> DISPOSED
Task was destroyed but it is pending!
task: <Task pending name='Task-22' coro=<TDAmeritradeMarketDataClient.submit_in_a_sec() running at /app/vscode/appdata/nautilus_sandbox/tda_adapter/data.py:150> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-23' coro=<TDAmeritradeMarketDataClient.submit_in_a_sec() running at /app/vscode/appdata/nautilus_sandbox/tda_adapter/data.py:150> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-24' coro=<TDAmeritradeMarketDataClient.submit_in_a_sec() running at /app/vscode/appdata/nautilus_sandbox/tda_adapter/data.py:150> wait_for=<Future pending cb=[Task.task_wakeup()]>>

**Comment by cjdsellers** [comment]
Hi Brett,

You'll notice the control flow and logging for `TradingNode` is vastly improved. Hopefully this makes the debugging easier for you. Please let me know how you go.

**Comment by cjdsellers** [comment]
Just read some of your question again. You could try increasing the timeouts in the config, e.g. the defaults currently:
```
    timeout_connection=10.0,
    timeout_reconciliation=10.0,
    timeout_portfolio=10.0,
    timeout_disconnection=10.0,
    timeout_post_stop=10.0,
```

If all clients aren't connected within the connect timeout, then the node will stop and dispose.

**Comment by cjdsellers** [comment]
Closing this awaiting feedback on the above. Feel free to open the issue again with an update, alternatively you could open a new issue reporting a specific bug, or a specific feature request. Many thanks!
