### ISSUE TITLE
Type Error | Interactive Brokers Provider

### ISSUE THREAD

**Issue by jordanparker6** [nautechsystems/nautilus_trader#685]
# Bug Report

Running into a type error with the IB adapter's provider. Looking at the type definitions for `provider.load_all` and its dependents, None appears to be accepted. 

### Expected Behavior

Load the instruments from the provider.

### Actual Behavior

```
/Users/jordanparker/Programs/crypto-data-pull/datapuller/nautilus.py:78: DeprecationWarning: There is no current event loop
  provider.load_all()
Traceback (most recent call last):
  File "/Users/jordanparker/Programs/crypto-data-pull/datapuller/nautilus.py", line 96, in <module>
    main()
  File "/Users/jordanparker/Programs/crypto-data-pull/datapuller/nautilus.py", line 78, in main
    provider.load_all()
  File "nautilus_trader/common/providers.pyx", line 177, in nautilus_trader.common.providers.InstrumentProvider.load_all
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/jordanparker/Library/Caches/pypoetry/virtualenvs/datapuller-KhKS4Jb5-py3.10/lib/python3.10/site-packages/nautilus_trader/adapters/interactive_brokers/providers.py", line 85, in load_all_async
    await self.load(**filters)
TypeError: nautilus_trader.adapters.interactive_brokers.providers.InteractiveBrokersInstrumentProvider.load() argument after ** must be a mapping, not NoneType
```

### Steps to Reproduce the Problem

```py
from nautilus_trader.config import InstrumentProviderConfig
from nautilus_trader.common.clock import LiveClock
from nautilus_trader.common.logging import Logger
from nautilus_trader.persistence.catalog import DataCatalog
from nautilus_trader.persistence.external.core import write_objects
from nautilus_trader.adapters.interactive_brokers.factories import get_cached_ib_client
from nautilus_trader.adapters.interactive_brokers.providers import InteractiveBrokersInstrumentProvider

 catalog = DataCatalog("PATH")
 clock = LiveClock()
 logger = Logger(clock)

client = get_cached_ib_client(
    username=os.environ["TWS_USERNAME"],
    password=os.environ["TWS_PASSWORD"],
    start_gateway=False,
)

provider = InteractiveBrokersInstrumentProvider(
    client=client, 
    config=InstrumentProviderConfig(load_all=True), 
     logger=logger
)

provider.load_all()
instruments = provider.get_all()
write_objects(catalog, instruments.values())
```

### Specifications

- OS platform: macOS Big Sur
- Python version: 3.10
- `nautilus_trader` version:   nautilus-trader = {extras = ["ib"], version = "^1.147.1"}

**Comment by limx0** [comment]
@jordanparker6 this should be closed by #713 (and release 1.149.0), please reopen if you see it again.
