### ISSUE TITLE
IB: orderbook snapshots L1 value assertion

### ISSUE THREAD

**Issue by niks199** [nautechsystems/nautilus_trader#712]
# Bug Report
Value (Ticker(contract=Contract(secType='STK', conId=265598, symbol='AAPL', exchange='SMART', primaryExchange='NASDAQ', currency='USD', localSymbol='AAPL', tradingClass='NMS'), time=datetime.datetime(2022, 7, 25, 12, 34, 4, 936179, tzinfo=datetime.timezone.utc)),) caused exception for event Event<updateEvent, [[None, <weakref at 0x11edbcb80; to 'InteractiveBrokersDataClient' at 0x11e197140>, <function InteractiveBrokersDataClient._on_top_level_snapshot at 0x11cde8af0>], [None, <weakref at 0x11edbcae0; to 'InteractiveBrokersDataClient' at 0x11e197140>, <function InteractiveBrokersDataClient._on_trade_ticker_update at 0x11cde8c10>], [functools.partial(<bound method InteractiveBrokersDataClient._on_quote_tick_update of InteractiveBrokersDataClient-InteractiveBrokers>, contract=Contract(secType='STK', conId=265598, symbol='AAPL', exchange='SMART', primaryExchange='NASDAQ', currency='USD', localSymbol='AAPL', tradingClass='NMS')), None, None]]>
Traceback (most recent call last):
  File "[..]/pypoetry/virtualenvs/equity-pair-trader-lDqPLG_e-py3.10/lib/python3.10/site-packages/eventkit/event.py", line 191, in emit
    result = obj(*args)
  File "[..]/pypoetry/virtualenvs/equity-pair-trader-lDqPLG_e-py3.10/lib/python3.10/site-packages/nautilus_trader/adapters/interactive_brokers/data.py", line 261, in _on_quote_tick_update
    bid_size=Quantity.from_str(str(tick.bidSize)) if tick.bidSize else None,
  File "nautilus_trader/model/objects.pyx", line 367, in nautilus_trader.model.objects.Quantity.from_str
  File "nautilus_trader/model/objects.pyx", line 306, in nautilus_trader.model.objects.Quantity.from_str_c
  File "nautilus_trader/model/objects.pyx", line 84, in nautilus_trader.model.objects.Quantity.__init__
  File "nautilus_trader/core/correctness.pyx", line 57, in nautilus_trader.core.correctness.Condition.true
ValueError: quantity negative, was nan
[..]/pypoetry/virtualenvs/equity-pair-trader-lDqPLG_e-py3.10/lib/python3.10/site-packages/nautilus_trader/live/node.py:339: UserWarning: on_stop was called when not overridden
  self.kernel.trader.stop()
[..]/pypoetry/virtualenvs/equity-pair-trader-lDqPLG_e-py3.10/lib/python3.10/site-packages/nautilus_trader/live/node.py:347: UserWarning: on_dispose was called when not overridden
  self.kernel.trader.dispose()
Traceback (most recent call last):
  ...
  File "[..]/pypoetry/virtualenvs/equity-pair-trader-lDqPLG_e-py3.10/lib/python3.10/site-packages/nautilus_trader/live/node.py", line 288, in start
    self.kernel.loop.run_until_complete(self._run())
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "[..]/pypoetry/virtualenvs/equity-pair-trader-lDqPLG_e-py3.10/lib/python3.10/site-packages/nautilus_trader/live/node.py", line 467, in _run
    await self.kernel.data_engine.get_run_queue_task()
  File "nautilus_trader/live/data_engine.pyx", line 305, in _run_data_queue
  File "nautilus_trader/data/engine.pyx", line 1053, in nautilus_trader.data.engine.DataEngine._handle_data
  File "nautilus_trader/data/engine.pyx", line 1083, in nautilus_trader.data.engine.DataEngine._handle_order_book_data
  File "nautilus_trader/msgbus/bus.pyx", line 449, in nautilus_trader.msgbus.bus.MessageBus.publish_c
  File "nautilus_trader/data/engine.pyx", line 1186, in nautilus_trader.data.engine.DataEngine._maintain_order_book
  File "nautilus_trader/data/engine.pyx", line 1195, in nautilus_trader.data.engine.DataEngine._maintain_order_book
  File "nautilus_trader/model/orderbook/book.pyx", line 292, in nautilus_trader.model.orderbook.book.OrderBook.apply
  File "nautilus_trader/model/orderbook/book.pyx", line 263, in nautilus_trader.model.orderbook.book.OrderBook.apply_snapshot
  File "nautilus_trader/model/orderbook/book.pyx", line 938, in nautilus_trader.model.orderbook.book.L1OrderBook.update
  File "nautilus_trader/model/orderbook/book.pyx", line 349, in nautilus_trader.model.orderbook.book.OrderBook._update
  File "nautilus_trader/model/orderbook/ladder.pyx", line 120, in nautilus_trader.model.orderbook.ladder.Ladder.update
  File "nautilus_trader/model/orderbook/ladder.pyx", line 95, in nautilus_trader.model.orderbook.ladder.Ladder.add
  File "nautilus_trader/model/orderbook/level.pyx", line 84, in nautilus_trader.model.orderbook.level.Level.add
  File "nautilus_trader/core/correctness.pyx", line 305, in nautilus_trader.core.correctness.Condition.equal
ValueError: The 'order.price' <class 'float'> of nan was not equal to the 'self.price' <class 'float'> of nan

And process exits with 1

### Expected Behavior
Add here...

### Actual Behavior
Add here...

### Steps to Reproduce the Problem

1.
2.
3.

### Specifications

- OS platform:
- Python version:
- `nautilus_trader` version:

**Comment by limx0** [comment]
@niks199 this should be closed in #713, please reopen if you see the issue again.
