### ISSUE TITLE
Backtest engine does not properly handle MarketIfTouched orders

### ISSUE THREAD

**Issue by miller-moore** [nautechsystems/nautilus_trader#716]
# Bug Report
Traceback (most recent call last):
  File "\~/scratch/test_backtest2.py", line 188, in <module>
    results: list[BacktestResult] = node.run()
  File "\~/venv/lib/python3.10/site-packages/nautilus_trader/backtest/node.py", line 125, in run
    result = self._run(
  File "\~/venv/lib/python3.10/site-packages/nautilus_trader/backtest/node.py", line 291, in _run_oneshot
    engine.run(run_config_id=run_config_id)
  File "nautilus_trader/backtest/engine.pyx", line 619, in nautilus_trader.backtest.engine.BacktestEngine.run
  File "nautilus_trader/backtest/engine.pyx", line 782, in nautilus_trader.backtest.engine.BacktestEngine._run
  File "nautilus_trader/backtest/exchange.pyx", line 620, in nautilus_trader.backtest.exchange.SimulatedExchange.process_bar
  File "nautilus_trader/backtest/exchange.pyx", line 645, in nautilus_trader.backtest.exchange.SimulatedExchange.process_bar
  File "nautilus_trader/backtest/exchange.pyx", line 676, in nautilus_trader.backtest.exchange.SimulatedExchange._process_trade_ticks_from_bar
  File "nautilus_trader/backtest/exchange.pyx", line 1240, in nautilus_trader.backtest.exchange.SimulatedExchange._iterate_matching_engine
  File "nautilus_trader/backtest/exchange.pyx", line 1257, in nautilus_trader.backtest.exchange.SimulatedExchange._iterate_side
  File "nautilus_trader/backtest/exchange.pyx", line 1263, in nautilus_trader.backtest.exchange.SimulatedExchange._match_order
  File "nautilus_trader/backtest/exchange.pyx", line 1276, in nautilus_trader.backtest.exchange.SimulatedExchange._match_stop_market_order
  File "nautilus_trader/backtest/exchange.pyx", line 1460, in nautilus_trader.backtest.exchange.SimulatedExchange._fill_market_order
  File "nautilus_trader/backtest/exchange.pyx", line 1408, in nautilus_trader.backtest.exchange.SimulatedExchange._determine_market_price_and_volume
AttributeError: 'nautilus_trader.model.orders.market_if_touched.Mar' object has no attribute 'price'

### Expected Behavior
For ``SimulatedExchange`` to handle all order types.

### Actual Behavior
Add here...

### Steps to Reproduce the Problem

1. Run [the EMACrossStopEntryTrail backtest example](https://github.com/nautechsystems/nautilus_trader/blob/dc493c5f4fbf19fb7d81913eb2599511b774e917/nautilus_trader/examples/strategies/ema_cross_stop_entry_trail.py)
2.
3.

### Specifications

- OS platform: macOS 12.4 (Darwin 21.5.0)
- Python version: 3.10.4
- `nautilus_trader` version: 1.148.0

**Comment by cjdsellers** [comment]
Fixed with f645deb76c2bc8558266c475f7a609c8e364872a on the `develop` branch. 

I'll bring the next release forward by a week to get this in. So very likely releasing `1.150.0` in about a weeks time.
