### ISSUE TITLE
Binance Futures Funding Rate Message in Account Update raises Error

### ISSUE THREAD

**Issue by stocktiger** [nautechsystems/nautilus_trader#728]
# Bug Report
I am currently getting errors when processing funding rate account updates on binance futures, which occurs every 8 hours. (noticeable cause the error occurs every 8h)

### Expected Behavior
No error.

### Actual Behavior
```
2022-08-12T16:00:00.861216400Z [ERR] TESTER-001.ExecClient-BINANCE: Error on handling b'{"stream":"9p2bRWN8zNmzGGnw5svDyPHVkrA83SnQUzQhVSzPZM8Qir4z8LZDa8qcG42JB345","data":{"e":"ACCOUNT_UPDATE","T":1660320000261,"E":1660320000428,"a":{"B":[{"a":"USDT","wb":"2378.63093384","cw":"2378.63093384","bc":"-0.09507796"}],"P":[],"m":"FUNDING_FEE"}}}'
ValueError(locked was negative)
Traceback (most recent call last):
  File "/home/michael/miniconda3/envs/trading/lib/python3.9/site-packages/nautilus_trader/adapters/binance/futures/execution.py", line 804, in _handle_user_ws_message
    self._handle_account_update(msg.data)
  File "/home/michael/miniconda3/envs/trading/lib/python3.9/site-packages/nautilus_trader/adapters/binance/futures/execution.py", line 819, in _handle_account_update
    balances=parse_account_balances_ws(raw_balances=msg.a.B),
  File "/home/michael/miniconda3/envs/trading/lib/python3.9/site-packages/nautilus_trader/adapters/binance/futures/parsing/account.py", line 53, in parse_account_balances_ws
    balance = AccountBalance(
  File "nautilus_trader/model/objects.pyx", line 1053, in nautilus_trader.model.objects.AccountBalance.__init__
    Condition.true(locked.raw_int64_c() >= 0, "locked was negative")
  File "nautilus_trader/core/correctness.pyx", line 57, in nautilus_trader.core.correctness.Condition.true
    raise make_exception(
```
### Steps to Reproduce the Problem

1. Run during funding rate credit/debit on binance futures 
2.
3.

### Specifications

- OS platform: wsl
- Python version: 3.9
- `nautilus_trader` version: 1.149.0 beta

**Comment by cjdsellers** [comment]
c043faa444c504411f3c6fd0e10d185c8f85524c now fixes the parsing of this message for the `develop` branch, basically avoiding the negative balance. Pending a complete overhaul of accounting. 

Closing for now.
