### ISSUE TITLE
Reconnection issues with FTX

### ISSUE THREAD

**Issue by limx0** [nautechsystems/nautilus_trader#733]
# Bug Report

FTX fails to reconnect (maybe from a temporary network issue?)  

### Expected Behavior
We should gracefully reconnect.

### Actual Behavior

Crash

### Stack

```
2022-08-18T16:52:39.074676633Z [WRN] TESTER-001.FTXWebSocketClient: [RECV] WSMessage(type=<WSMsgType.CLOSED: 257>, data=None, extra=None).
2022-08-18T16:52:39.074684658Z [WRN] TESTER-001.FTXWebSocketClient: ConnectionAbortedError: Reconnecting self.connection_retry_count=0, self.max_retry_connection=6
2022-08-18T16:52:39.074687022Z [DBG] TESTER-001.FTXWebSocketClient: Attempting reconnect (attempt: 1).
2022-08-18T16:52:39.074688815Z [DBG] TESTER-001.FTXWebSocketClient: Reconnecting WebSocket to wss://ftx.com/ws/
2022-08-18T16:52:49.086996623Z [ERR] TESTER-001.FTXWebSocketClient: Error on receive
ClientConnectorError(Cannot connect to host ftx.com:443 ssl:default [Temporary failure in name resolution])
Traceback (most recent call last):
  File "/home/user/lib/python3.10/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/home/user/lib/python3.10/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/home/user/lib/python3.10/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "uvloop/loop.pyx", line 1514, in getaddrinfo
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "nautilus_trader/network/websocket.pyx", line 262, in nautilus_trader.network.websocket.WebSocketClient.start
  File "nautilus_trader/network/websocket.pyx", line 245, in receive
  File "nautilus_trader/network/websocket.pyx", line 151, in reconnect
  File "/home/user/lib/python3.10/site-packages/aiohttp/client.py", line 776, in _ws_connect
    resp = await self.request(
  File "/home/user/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/home/user/lib/python3.10/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/user/lib/python3.10/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/user/lib/python3.10/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
```

### Specifications

- OS platform: linux
- Python version:
- `nautilus_trader` version: 1.150.0

**Comment by cjdsellers** [comment]
Looks like that exception was raised during a reconnect attempt, so for now I'm just surrounding the reconnect with a try except:
```
            try:
                await self.reconnect()
            except aiohttp.ClientConnectorError:
                # Robust to connection errors during reconnect attempts
                pass
```
Just so it'll get to go through another few attempts with backoffs depending on how many there have been.

Closing for now, please report any further connection issues!
