### ISSUE TITLE
Loading External Data

### ISSUE THREAD

**Issue by s100166** [nautechsystems/nautilus_trader#754]
# Code
```py
start = dt_to_unix_nanos(pd.Timestamp('2022-08-01', tz='UTC'))
end = dt_to_unix_nanos(pd.Timestamp('2020-08-15', tz='UTC'))

catalog.quote_ticks(start=start, end=end)
```

I got this from nautilus docs on `Loading External Data` and then i got an error
```console
Traceback (most recent call last):
  File "c:\Users\PC\Desktop\Dev\Python\nautilus-trader\backtest\main.py", line 89, in <module>
    catalog.quote_ticks(start=start, end=end)
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nautilus_trader\persistence\catalog\base.py", line 232, in quote_ticks
    return self.query(
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nautilus_trader\persistence\catalog\base.py", line 148, in query
    return self._query(
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nautilus_trader\persistence\catalog\parquet.py", line 126, in _query
    return self._handle_table_dataframe(
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nautilus_trader\persistence\catalog\parquet.py", line 152, in _handle_table_dataframe
    kw = [f"{k}={local_vars[k]}" for k in ("filter_expr", "instrument_ids", "start", "end")]
  File "C:\Users\PC\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\nautilus_trader\persistence\catalog\parquet.py", line 152, in <listcomp>
    kw = [f"{k}={local_vars[k]}" for k in ("filter_expr", "instrument_ids", "start", "end")]
KeyError: 'filter_expr'
```

**Comment by cjdsellers** [comment]
Now resolved on `develop`
