### ISSUE TITLE
Pair LUNC/BUSD cause value error on startup during bar retrieve step on binance spot

### ISSUE THREAD

**Issue by gaugau3000** [nautechsystems/nautilus_trader#789]
# Bug Report

### Expected Behavior
No error message

### Actual Behavior

> ValueError: invalid `value` greater than `QUANTITY_MAX` 18_446_744_073.0, was 28_367_292_769.36

```
2022-09-26T13:55:59.728965247Z [INF] TESTER-001.TESTER-001: RUNNING.
2022-09-26T13:55:59.728972261Z [INF] TESTER-001.TradingNode: RUNNING.
Task exception was never retrieved
future: <Task finished name='Task-25' coro=<BinanceSpotDataClient._request_bars() done, defined at /usr/local/pip-global/nautilus_trader/adapters/binance/spot/data.py:520> exception=ValueError('invalid `value` greater than `QUANTITY_MAX` 18_446_744_073.0, was 28_367_292_769.36')>
Traceback (most recent call last):
  File "/usr/local/pip-global/nautilus_trader/adapters/binance/spot/data.py", line 559, in _request_bars
    bars: List[BinanceBar] = [
  File "/usr/local/pip-global/nautilus_trader/adapters/binance/spot/data.py", line 560, in <listcomp>
    parse_bar_http(
  File "/usr/local/pip-global/nautilus_trader/adapters/binance/common/parsing/data.py", line 70, in parse_bar_http
    volume=Quantity.from_str(values[5]),
  File "nautilus_trader/model/objects.pyx", line 400, in nautilus_trader.model.objects.Quantity.from_str
  File "nautilus_trader/model/objects.pyx", line 333, in nautilus_trader.model.objects.Quantity.from_str_c
  File "nautilus_trader/model/objects.pyx", line 107, in nautilus_trader.model.objects.Quantity.__init__
ValueError: invalid `value` greater than `QUANTITY_MAX` 18_446_744_073.0, was 28_367_292_769.36
```

### Steps to Reproduce the Problem

1. Load 1 minute timeframe candles on LUNC/BUSD spot market on binance.
2. Run a strategy that load subscribe to bars

### Specifications

- OS platform: linux
- Python version: 3.9.13
- `nautilus_trader` version: 1.155.0

**Comment by cjdsellers** [comment]
So this looks like the `volume` field judging by its position in the values.

The only course of action to correct this would be to change the type of `volume` from `Quantity` to `decimal.Decimal` which would then start compromising the correctness and performance of the entire platform, and is a slippery slope.

So I think the only course of action here if you really wanted to trade this product would be to create a custom adapter and a custom data type - something like `LargeBar`, which doesn't use the built in high-performance value objects (use `decimal.Decimal`), which is clearly a lot of work.

I actually think considering all the edge case areas this exceedance of max quantity could occur with Binance, I'm going to close the issue as the error message is clear enough I can understand what happened without referring to anything more than the `BinanceBar` class definition.

As a general stance I think we can't support these assets with enormous values due to their low underlying unit value.

Many thanks for the report! and hope trading is otherwise going well for you :pray:
