### ISSUE TITLE
Bot start on FTX futures exchange -> problem generating trade report

### ISSUE THREAD

**Issue by gaugau3000** [nautechsystems/nautilus_trader#799]
# Bug Report

### Expected Behavior
No error message

### Actual Behavior

```
2022-10-03T18:11:03.588702885Z [INF] TESTER-001.ExecClient-FTX: Generating ExecutionMassStatus for FTX...
2022-10-03T18:11:03.588765194Z [INF] TESTER-001.ExecClient-FTX: Generating OrderStatusReports for FTX...
2022-10-03T18:11:03.589053835Z [INF] TESTER-001.ExecClient-FTX: Generating TradeReports for FTX...
2022-10-03T18:11:03.589282894Z [INF] TESTER-001.ExecClient-FTX: Generating PositionStatusReports for FTX...
2022-10-03T18:11:03.939116645Z [INF] TESTER-001.ExecClient-FTX: Generated 0 TradeReports.
2022-10-03T18:11:03.974565033Z [ERR] TESTER-001.ExecClient-FTX: Cannot generate position status report: no instrument found for CEL-PERP.FTX.
2022-10-03T18:11:03.974612471Z [ERR] TESTER-001.ExecClient-FTX: Cannot generate position status report: no instrument found for ALT-PERP.FTX.
2022-10-03T18:11:03.974613741Z [INF] TESTER-001.ExecClient-FTX: Generated 0 PositionStatusReports.
2022-10-03T18:11:04.764067482Z [ERR] TESTER-001.ExecClient-FTX: Cannot generate trade report: 
FTXClientError()
Traceback (most recent call last):
  File "/usr/local/pip-global/nautilus_trader/adapters/ftx/http/client.py", line 138, in _send_request
    resp: ClientResponse = await self.request(
  File "nautilus_trader/network/http.pyx", line 173, in request
  File "nautilus_trader/network/http.pyx", line 180, in nautilus_trader.network.http.HttpClient.request
  File "/usr/local/pip-global/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 429, message='Too Many Requests', url=URL('https://ftx.com/api/conditional_orders/174803174/triggers')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/pip-global/nautilus_trader/adapters/ftx/execution.py", line 397, in _get_trigger_order_status_reports
    trigger_reports = await asyncio.gather(
  File "/usr/local/pip-global/nautilus_trader/adapters/ftx/http/client.py", line 287, in get_trigger_order_triggers
    return await self._sign_request(
  File "/usr/local/pip-global/nautilus_trader/adapters/ftx/http/client.py", line 116, in _sign_request
    return await self._send_request(
  File "/usr/local/pip-global/nautilus_trader/adapters/ftx/http/client.py", line 145, in _send_request
    await self._handle_exception(e)
  File "/usr/local/pip-global/nautilus_trader/adapters/ftx/http/client.py", line 160, in _handle_exception
    raise FTXClientError(
```

This error message don't stop the bot.

### Steps to Reproduce the Problem

1. Run an instance on the bot on FTX futures

### Specifications

- OS platform: Linux
- Python version: 3.9.14
- `nautilus_trader` version: 1.155.0

**Comment by cjdsellers** [comment]
I'm not sure halting the trading node on a 429 should be the default behavior? at least it should be configurable I think

The lack of rate limiting for HTTP requests is becoming a running theme for issues though #780 

Which brings this higher up on the list of priorities #547

Ideally requests will be throttled with a timeout for what an acceptable delay is?
