### ISSUE TITLE
InteractiveBrokers Client connectivity

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#812]
# Bug Report
IB Adapter example code in `nautilus_trader-master/examples/live/interactive_brokers_example.py`.
```python
data_clients = {
    "IB": InteractiveBrokersDataClientConfig(
        gateway_host="127.0.0.1",
        start_gateway=False,
        instrument_provider=InstrumentProviderConfig(
            load_all=True,
            filters=tuple(
                {
                    "secType": "STK",
                    "symbol": "SEC0",
                    "exchange": "BVME.ETF",
                    # "currency": "USD",
                }.items()
            ),
        ),
    ),
}
```

It doesn't work and fails for number of reasons:
1. Firstly in `load_all_async` of ib_provider, tuple will iterate with ('secType', 'STK') cause the below traceback.
2. Even above is fixed, ibapi will not return contracts i.e more vague request which is request all the stocks. Even though its result is list it expects the query result to be more precise.
3. Following is the traceback result.
```shell
Task exception was never retrieved
future: <Task finished name='Task-15' coro=<InteractiveBrokersDataClient._connect() done, defined at /tmp/pycharm_project_359/project/nautilus_trader/adapters/interactive_brokers/data.py:119> exception=ValueError('dictionary update sequence element #0 has length 7; 2 is required') created at /tmp/pycharm_project_359/project/nautilus_trader/adapters/interactive_brokers/data.py:117>
source_traceback: Object created at (most recent call last):
  File "/tmp/pycharm_project_359/main.py", line 8, in <module>
    self = MyTradingNode()
  File "/tmp/pycharm_project_359/project/ntTrade.py", line 227, in __init__
    self.node.start()
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/live/node.py", line 288, in start
    self.kernel.loop.run_until_complete(self._run())
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/live/node.py", line 405, in _run
    self.kernel.data_engine.connect()
  File "/tmp/pycharm_project_359/project/nautilus_trader/adapters/interactive_brokers/data.py", line 117, in connect
    self._loop.create_task(self._connect())
Traceback (most recent call last):
  File "/tmp/pycharm_project_359/project/nautilus_trader/adapters/interactive_brokers/data.py", line 126, in _connect
    await self.instrument_provider.initialize()
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/common/providers.py", line 161, in initialize
    await self.load_all_async(self._filters)
  File "/tmp/pycharm_project_359/project/nautilus_trader/adapters/interactive_brokers/providers.py", line 87, in load_all_async
    filt = dict(f)
ValueError: dictionary update sequence element #0 has length 7; 2 is required
```

### Expected Behavior
This is the working example without any modification on adapter code.
1. The solution is to make sure all this criteria i.e secType, symbol, exchange goes to provider as single tuple 
2. The below example uses a helper function to convert the required symbols in packed dict format which is acceptable by ib adapter 

```python
def dict_to_tuple_for_ib_provider(tickers_dict):
    class hashabledict(dict):
        def __hash__(self):
            return hash(tuple(sorted(self.items())))
    tickers_list = []
    for secType in tickers_dict:
        for exchange in tickers_dict[secType]:
            for ticker in tickers_dict[secType][exchange]:
                if secType=='STK':
                    tickers_list.append(hashabledict(dict(secType=secType, localSymbol=ticker, exchange='SMART', primaryExchange=exchange)))
                else:
                    tickers_list.append(hashabledict(dict(secType=secType, localSymbol=ticker, exchange=exchange)))
    return {"filters": tuple(set(tickers_list))}

local_symbols = {'CASH': {'IDEALPRO': ['EUR.USD', 'GBP.USD']},
                        'STK': {'NASDAQ': ['AAPL', 'AMZN']},
}

data_clients = {
    "IB": InteractiveBrokersDataClientConfig(
        gateway_host="127.0.0.1",
        start_gateway=False,
        instrument_provider=InstrumentProviderConfig(
            load_all=True,
            filters=dict_to_tuple_for_ib_provider(local_symbols),
        ),
    ),
}
```

### Steps to Reproduce the Problem

1. Issue can be reproduced by use the original example will produce traceback result. To avoid the docker complexity and start the IB Gateway, `start_gateway=False` to disable gateway starting errors. It will simply connect the already running Gateway
2. Expected and working behavior can be produced by using the modified example provided

### Specifications

- OS platform: Ubuntu 20.04.5 LTS
- Python version: 3.9
- `nautilus_trader` version: 1.155.0

**Comment by limx0** [comment]
Hey @rsmb7z thanks for the report! This should be fixed by #857, please let us know if you see any more issues.
