### ISSUE TITLE
InteractiveBrokers parsing instruments

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#813]
# Bug Report
When forex contract details are received by IB Instrument Provider. Following is the traceback result.

```shell
2022-10-17T12:37:58.323366607Z [DBG] TESTER-001.InteractiveBrokersInstrumentProvider: Attempting to create instrument from ContractDetails(contract=Contract(secType='CASH', conId=12087792, symbol='EUR', exchange='IDEALPRO', currency='USD', localSymbol='EUR.USD', tradingClass='EUR.USD'), marketName='EUR.USD', minTick=5e-05, orderTypes='ACTIVETIM,AD,ADJUST,ALERT,ALGO,ALLOC,AVGCOST,BASKET,CASHQTY,COND,CONDORDER,DAY,DEACT,DEACTDIS,DEACTEOD,GAT,GTC,GTD,GTT,HID,IOC,LIT,LMT,MIT,MKT,NONALGO,OCA,REL,RELPCTOFS,SCALE,SCALERST,STP,STPLMT,TRAIL,TRAILLIT,TRAILLMT,TRAILMIT,WHATIF', validExchanges='IDEALPRO', priceMagnifier=1, underConId=0, longName='European Monetary Union Euro', contractMonth='', industry='', category='', subcategory='', timeZoneId='US/Eastern', tradingHours='20221016:1715-20221017:1700;20221017:1715-20221018:1700;20221018:1715-20221019:1700;20221019:1715-20221020:1700;20221020:1715-20221021:1700', liquidHours='20221016:1715-20221017:1700;20221017:1715-20221018:1700;20221018:1715-20221019:1700;20221019:1715-20221020:1700;20221020:1715-20221021:1700', evRule='', evMultiplier=0, mdSizeMultiplier=1, aggGroup=4, underSymbol='', underSecType='', marketRuleIds='239', secIdList=[], realExpirationDate='', lastTradeTime='', stockType='', minSize=1.0, sizeIncrement=1.0, suggestedSizeIncrement=1.0, cusip='', ratings='', descAppend='', bondType='', couponType='', callable=False, putable=False, coupon=0, convertible=False, maturity='', issueDate='', nextOptionDate='', nextOptionType='', nextOptionPartial=False, notes='')
Task exception was never retrieved
future: <Task finished name='Task-15' coro=<InteractiveBrokersDataClient._connect() done, defined at /home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/adapters/interactive_brokers/data.py:116> exception=AttributeError("'ContractDetails' object has no attribute 'sizeMinTick'") created at /home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/adapters/interactive_brokers/data.py:114>
source_traceback: Object created at (most recent call last):
  File "/tmp/pycharm_project_359/main.py", line 8, in <module>
    self = MyTradingNode()
  File "/tmp/pycharm_project_359/project/ntTrade.py", line 206, in __init__
    self.node.start()
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/live/node.py", line 288, in start
    self.kernel.loop.run_until_complete(self._run())
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/live/node.py", line 405, in _run
    self.kernel.data_engine.connect()
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/adapters/interactive_brokers/data.py", line 114, in connect
    self._loop.create_task(self._connect())
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/adapters/interactive_brokers/data.py", line 123, in _connect
    await self.instrument_provider.initialize()
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/common/providers.py", line 161, in initialize
    await self.load_all_async(self._filters)
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/adapters/interactive_brokers/providers.py", line 88, in load_all_async
    await self.load(**filt)
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/adapters/interactive_brokers/providers.py", line 231, in load
    instrument: Instrument = parse_instrument(
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/adapters/interactive_brokers/parsing/instruments.py", line 71, in parse_instrument
    return parse_forex_contract(details=contract_details)
  File "/home/ubuntu/.virtualenvs/myTrader/lib/python3.9/site-packages/nautilus_trader/adapters/interactive_brokers/parsing/instruments.py", line 178, in parse_forex_contract
    size_increment=Quantity(details.sizeMinTick or 1, 1),
AttributeError: 'ContractDetails' object has no attribute 'sizeMinTick'
```

### Expected Behavior
IB ContractDetails doesn't have `sizeMinTick`, it should be `sizeIncrement`.

### Actual Behavior
Shouldn't produce error.

### Steps to Reproduce the Problem

1. Request forex instrument from Instrument Provider i.e. EUR.USD

### Specifications

- OS platform: Ubuntu 20.04.5 LTS
- Python version: 3.9
- `nautilus_trader` version: 1.155.0

**Comment by limx0** [comment]
This should be fixed by #857, please let us know if you see any more issues.
