### ISSUE TITLE
Potential memory leak in backtesting

### ISSUE THREAD

**Issue by Tzumx** [nautechsystems/nautilus_trader#880]
# Bug Report
In backtesting in case we use a lot of data (like 2 millions QuoteTicks from Binance), we get continuous rising of allocated memory.
So as a result, we see consumption of about 20 Gb memory after a few weeks of backtesting.
We were trying to delete instances of QuoteTicks by hand, but with partial success only.

### Expected Behavior
Used instances of Data (QuoteTicks) should be properly delete / collected by garbage collector.

### Actual Behavior
Looks like instances of Data (QuoteTicks) remains alive and consume memory

### Steps to Reproduce the Problem
Example:
https://github.com/limitless-galaxy/memory_leak
1. Take any strategy (signal_strategy from nautilus examples)
2. Generate about 2 million QuoteTicks per day
3. Send it to the backtesting
![2022-11-29 22_38_24-](https://user-images.githubusercontent.com/91601062/204665958-4fa954b1-1399-4c05-aace-adad3ab4c962.png)

### Specifications

- OS platforms: Ubuntu 20.04 LTS, Mac
- Python version: 3.10.8
- `nautilus_trader` version: 1.160
- Test on AMD Ryzen 9 5950X, 4*32GB and local PCs

**Comment by cjdsellers** [comment]
Thanks so much for the detailed report Tzumx, we're looking into it!

**Comment by twitu** [comment]
So I'm trying to run this example as is to test out the recent changes but it's throwing a TypeError

```
Traceback (most recent call last):
  File "/home/twitu/Code/memory_leak/memory_leak/main.py", line 97, in <module>
    results = node.run()
  File "/home/twitu/.cache/pypoetry/virtualenvs/memory-leak-QUzA9TVd-py3.10/lib/python3.10/site-packages/nautilus_trader/backtest/node.py", line 127, in run
    run_config_id=config.id,
  File "/home/twitu/.cache/pypoetry/virtualenvs/memory-leak-QUzA9TVd-py3.10/lib/python3.10/site-packages/nautilus_trader/config/backtest.py", line 224, in id
    return tokenize_config(self.dict())
  File "/home/twitu/.cache/pypoetry/virtualenvs/memory-leak-QUzA9TVd-py3.10/lib/python3.10/site-packages/nautilus_trader/config/backtest.py", line 265, in tokenize_config
    value: bytes = msgspec.json.encode(obj, enc_hook=encoder)
  File "/home/twitu/.cache/pypoetry/virtualenvs/memory-leak-QUzA9TVd-py3.10/lib/python3.10/site-packages/nautilus_trader/config/backtest.py", line 261, in encoder
    raise TypeError(f"Objects of type {type(x)} are not supported")
TypeError: Objects of type <class 'datetime.datetime'> are not supported
```

The only change is to `pypoetry.toml` to use my installed python version and my local nautilus directory.

```
python = "3.10.6"
nautilus-trader = { path="../nautilus_trader/", develop=false}
```

Did you make some tweaks to get this to work?

**Comment by pyinto** [comment]
@twitu, hmm, worked for me, but I see there is an error in datetime annotations, just pushed a fix, please check

**Comment by pyinto** [comment]
@twitu Did you manage to run and reproduce the leakage? I don't see any significant changes after updating to the latest 1.62 release and upgrading python version up to 3.11.1.

Also just want to add that it's not about backtesting we have the same issue on a live node with 8GB of RAM, and it restarts every ~6hours. I'm curious how you guys run to avoid it and in which configuration 
@cjdsellers Let me know if you need more details, we are happy to help!
