### ISSUE TITLE
TypeError: 'kw_only' is an invalid keyword argument for StructMeta.__new__()

### ISSUE THREAD

**Issue by rsmb7z** [nautechsystems/nautilus_trader#927]
# Bug Report
Not sure if its just me or someone else is facing issue too after lastest master upgrade. Backtest and Live engine both not working as is related to NautilusConfig.

### Expected Behavior
Shouldn't raise exception.

### Actual Behavior
Raise exceptions
```
Traceback (most recent call last):
  File "C:\PycharmProjects\nautilus_trader\examples\backtest\fx_ema_cross_audusd_ticks.py", line 24, in <module>
    from nautilus_trader.backtest.engine import BacktestEngine
  File "nautilus_trader\\backtest\\engine.pyx", line 1, in init nautilus_trader.backtest.engine
  File "nautilus_trader\\common\\actor.pyx", line 32, in init nautilus_trader.common.actor
  File "C:\PycharmProjects\nautilus_trader\nautilus_trader\config\__init__.py", line 22, in <module>
    from nautilus_trader.config.backtest import BacktestDataConfig
  File "C:\PycharmProjects\nautilus_trader\nautilus_trader\config\backtest.py", line 26, in <module>
    from nautilus_trader.config.common import DataEngineConfig
  File "C:\PycharmProjects\nautilus_trader\nautilus_trader\config\common.py", line 36, in <module>
    class NautilusConfig(msgspec.Struct, kw_only=True):
TypeError: 'kw_only' is an invalid keyword argument for StructMeta.__new__()

Process finished with exit code 1
```

### Steps to Reproduce the Problem

1. Run `fx_ema_cross_audusd.ticks.py` from Backtest examples

### Specifications

- OS platform: Windows 10
- Python version: 3.10.6
- `nautilus_trader` version: 1.164.0

**Comment by cjdsellers** [comment]
Thanks for the report!

This appears to be fixed already though.
